-- T025 catalog only. Prepared for manual application to an isolated database.
begin;
create function pg_temp.assert_calendar(ok boolean,message text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception 'T025: %',message;end if;end $$;
select pg_temp.assert_calendar((select count(*)=10 from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relrowsecurity and ((n.nspname='public' and c.relname in ('calendar_accounts','calendar_sources','calendar_events','calendar_sync_runs')) or (n.nspname='app_private' and c.relname in ('google_credentials','google_event_links','google_calendar_cursors','google_oauth_flows','google_calendar_limits','google_sync_executions')))),'all public and private tables enable RLS');
select pg_temp.assert_calendar(not exists(select 1 from information_schema.role_table_grants where table_schema='app_private' and table_name in ('google_credentials','google_event_links','google_calendar_cursors','google_oauth_flows','google_calendar_limits','google_sync_executions') and grantee in ('anon','authenticated','service_role','PUBLIC')),'private tables unavailable even to service_role direct DML');
select pg_temp.assert_calendar(not exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name like 'calendar_%' and grantee in ('anon','authenticated','service_role','PUBLIC') and privilege_type<>'SELECT'),'no direct table mutations');
select pg_temp.assert_calendar(not exists(select 1 from information_schema.columns where table_schema='public' and table_name like 'calendar_%' and column_name ~ '(token|secret|code|verifier|cipher|digest|execution)'),'public calendar fields contain no credential or claim');
select pg_temp.assert_calendar(not exists(select 1 from information_schema.columns where table_schema='app_private' and table_name='google_oauth_flows' and column_name in ('code','verifier','access_token','refresh_token','email')),'OAuth flow stores digest and identity binding only');
select pg_temp.assert_calendar((select array_agg(column_name::text order by ordinal_position)=array['id','user_id','account_id','channel','status','calendar_count','event_count','started_at','finished_at'] from information_schema.columns where table_schema='public' and table_name='calendar_sync_runs'),'Admin audit contains metadata only');
select pg_temp.assert_calendar((select count(*)=4 from pg_policy where polrelid in ('public.calendar_accounts'::regclass,'public.calendar_sources'::regclass,'public.calendar_events'::regclass,'public.calendar_sync_runs'::regclass) and polcmd='r'),'only own-read policies');
select pg_temp.assert_calendar(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','app_private') and (p.proname like 'calendar_%' or p.proname like 'google_calendar_%') and (has_function_privilege('anon',p.oid,'EXECUTE') or has_function_privilege('authenticated',p.oid,'EXECUTE'))),'no callable private SDK boundary for browser');
select pg_temp.assert_calendar((select count(*)=3 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('google_calendar_call','google_calendar_jobs','google_calendar_admin_runs') and not p.prosecdef and has_function_privilege('service_role',p.oid,'EXECUTE')),'three invoker wrappers for service only');
select pg_temp.assert_calendar(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app_private' and (p.proname like 'calendar_%' or p.proname like 'google_calendar_%') and (not p.prosecdef or not p.proconfig @> array['search_path=""'])),'private definers have empty search_path');
select pg_temp.assert_calendar((select count(*)=1 from pg_constraint where conrelid='public.domain_events'::regclass and conname='domain_events_entity_type_check' and pg_get_constraintdef(oid) like '%calendar_account%' and pg_get_constraintdef(oid) like '%vault_metadata%' and pg_get_constraintdef(oid) like '%knowledge_page%'),'closed event union preserves previously shipped modules');
select pg_temp.assert_calendar(exists(select 1 from pg_constraint where conrelid='public.domain_events'::regclass and conname='vault_metadata_only'),'Vault metadata-only CHECK preserved');
select pg_temp.assert_calendar(exists(select 1 from pg_constraint where conrelid='public.domain_events'::regclass and conname='calendar_metadata_only'),'Calendar metadata-only CHECK');
rollback;
