-- T025 serial local specification. Requires EMPTY dedicated Auth fixture database.
-- All Google responses, ciphertext and credentials below are inert test values.
-- Rollback assertions do not prove remote OAuth, actual Google revocation or concurrency.
begin;
set local statement_timeout='30s';
set local app.cal_owner='25000000-0000-4000-8000-000000000001';
set local app.cal_other='25000000-0000-4000-8000-000000000002';
set local app.cal_session='25000000-0000-4000-8000-000000000011';
set local app.cal_other_session='25000000-0000-4000-8000-000000000012';
set local app.cal_execution='25000000-0000-4000-8000-000000000021';
set local app.cal_flow='25000000-0000-4000-8000-000000000031';
create function pg_temp.assert_calendar(ok boolean,message text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception 'T025: %',message;end if;end $$;
create function pg_temp.calendar_error(command text,expected text) returns void language plpgsql as $$ declare actual text;begin begin execute command;exception when others then get stacked diagnostics actual=returned_sqlstate;if actual<>expected then raise exception 'Expected %, got %: %',expected,actual,sqlerrm;end if;return;end;raise exception 'Expected failure %: %',expected,command;end $$;
do $$ declare temp_schema text;begin select nspname into strict temp_schema from pg_namespace where oid=pg_my_temp_schema();execute format('grant usage on schema %I to anon,authenticated,service_role',temp_schema);end $$;
grant execute on function pg_temp.assert_calendar(boolean,text),pg_temp.calendar_error(text,text) to anon,authenticated,service_role;
create function pg_temp.calendar_call(command text,input jsonb) returns jsonb language sql as $$ select public.google_calendar_call(current_setting('app.cal_owner')::uuid,current_setting('app.cal_session')::uuid,command,input,false,current_setting('app.cal_execution')::uuid) $$;
grant execute on function pg_temp.calendar_call(text,jsonb) to anon,authenticated,service_role;
select pg_temp.assert_calendar(not exists(select 1 from auth.users),'empty Auth fixture required');
insert into auth.users(id,aud,role,email,is_anonymous,created_at,updated_at) values(current_setting('app.cal_owner')::uuid,'authenticated','authenticated','t025-a@example.invalid',false,now(),now()),(current_setting('app.cal_other')::uuid,'authenticated','authenticated','t025-b@example.invalid',false,now(),now());
insert into auth.sessions(id,user_id,created_at,updated_at) values(current_setting('app.cal_session')::uuid,current_setting('app.cal_owner')::uuid,now(),now()),(current_setting('app.cal_other_session')::uuid,current_setting('app.cal_other')::uuid,now(),now());
set local role authenticated;
select pg_temp.calendar_error($q$select pg_temp.calendar_call('snapshot','{}')$q$,'42501');
select pg_temp.calendar_error('select * from app_private.google_credentials','42501');
reset role;
set local role service_role;
select pg_temp.calendar_error($q$select public.google_calendar_call(current_setting('app.cal_other')::uuid,current_setting('app.cal_session')::uuid,'snapshot','{}',false,current_setting('app.cal_execution')::uuid)$q$,'42501');
select set_config('app.cal_account',(pg_temp.calendar_call('flow_begin',jsonb_build_object('flow_id',current_setting('app.cal_flow'),'digest',repeat('a',64),'expires_at',now()+interval '9 minutes','reconnect_account',null))->>'account_id'),true);
select pg_temp.calendar_error($q$select pg_temp.calendar_call('flow_consume',jsonb_build_object('flow_id',current_setting('app.cal_flow'),'digest',repeat('b',64)))$q$,'23505');
select pg_temp.calendar_call('flow_consume',jsonb_build_object('flow_id',current_setting('app.cal_flow'),'digest',repeat('a',64)));
select pg_temp.calendar_error($q$select pg_temp.calendar_call('flow_consume',jsonb_build_object('flow_id',current_setting('app.cal_flow'),'digest',repeat('a',64)))$q$,'23505');
select pg_temp.calendar_call('connect',jsonb_build_object('flow_id',current_setting('app.cal_flow'),'account_id',current_setting('app.cal_account'),'google_sub','inert-sub','email','google@example.invalid','scopes',jsonb_build_array('openid','email','https://www.googleapis.com/auth/calendar.calendarlist.readonly','https://www.googleapis.com/auth/calendar.events.readonly'),'tokens',jsonb_build_object('version',1,'key_id','test','iv',repeat('A',16),'tag',repeat('A',22)||'==','ciphertext','AAAA'),'credential_version',1,'calendars',jsonb_build_array(jsonb_build_object('google_id','inert-source','name','Private calendar canary','color_key','calendar','deleted',false))));
select set_config('app.cal_source',(pg_temp.calendar_call('snapshot','{}')->'calendars'->0->>'id'),true);
select pg_temp.assert_calendar(not (pg_temp.calendar_call('snapshot','{}')::text ~ '(ciphertext|access_token|refresh_token|inert-sub|inert-source)'),'public DTO excludes credentials/provider identities');
select pg_temp.calendar_error($q$select public.google_calendar_call(current_setting('app.cal_other')::uuid,current_setting('app.cal_other_session')::uuid,'private_account',jsonb_build_object('account_id',current_setting('app.cal_account')),false,current_setting('app.cal_execution')::uuid)$q$,'23503');
select set_config('app.cal_run',(pg_temp.calendar_call('run',jsonb_build_object('account_id',current_setting('app.cal_account'),'client_id','sync-one','window',jsonb_build_object('start_day','2026-10-01','end_day','2026-11-01')))->>'id'),true);
select pg_temp.calendar_error($q$select public.google_calendar_call(current_setting('app.cal_owner')::uuid,current_setting('app.cal_session')::uuid,'run',jsonb_build_object('account_id',current_setting('app.cal_account'),'client_id','sync-one','window',jsonb_build_object('start_day','2026-10-01','end_day','2026-11-01')),false,'25000000-0000-4000-8000-000000000022')$q$,'40001');
select pg_temp.calendar_call('commit_events',jsonb_build_object('account_id',current_setting('app.cal_account'),'revision','0','calendar_id',current_setting('app.cal_source'),'run_id',current_setting('app.cal_run'),'window',jsonb_build_object('start_day','2026-10-01','end_day','2026-11-01'),'reset',true,'sync_token','inert-cursor','events',jsonb_build_array(jsonb_build_object('google_id','inert-event','cancelled',false,'title','Private meeting canary','starts_at','2026-10-09T03:00:00Z','ends_at','2026-10-12T03:00:00Z','all_day',true,'location',null,'html_link',null,'reminder_minutes',null))));
select set_config('app.cal_event',(pg_temp.calendar_call('snapshot','{}')->'items'->0->>'id'),true);
select pg_temp.assert_calendar(jsonb_array_length(pg_temp.calendar_call('snapshot','{}')->'items')=1,'committed event visible');
select pg_temp.calendar_call('finish_run',jsonb_build_object('run_id',current_setting('app.cal_run'),'status','complete','calendar_count',1,'event_count',1));
select pg_temp.assert_calendar(pg_temp.calendar_call('run',jsonb_build_object('account_id',current_setting('app.cal_account'),'client_id','sync-one','window',jsonb_build_object('start_day','2026-10-01','end_day','2026-11-01')))->>'status'='complete','successful sync receipt replays');
reset role;
create function pg_temp.reject_calendar_event() returns trigger language plpgsql as $$ begin if new.entity_type='calendar_source' then raise exception 'injected event failure' using errcode='P0001';end if;return new;end $$;
create trigger t025_reject_event before insert on public.domain_events for each row execute function pg_temp.reject_calendar_event();
set local role service_role;
select pg_temp.calendar_error($q$select pg_temp.calendar_call('select',jsonb_build_object('calendar_id',current_setting('app.cal_source'),'selected',false,'client_id','selection-rollback'))$q$,'P0001');
reset role;
select pg_temp.assert_calendar((select selected from public.calendar_sources where id=current_setting('app.cal_source')::uuid) and (select revision=1 from public.calendar_accounts where id=current_setting('app.cal_account')::uuid) and not exists(select 1 from app_private.command_receipts where client_id='selection-rollback'),'event failure rolls back selection/revision/receipt atomically');
drop trigger t025_reject_event on public.domain_events;
set local role service_role;
select pg_temp.calendar_call('select',jsonb_build_object('calendar_id',current_setting('app.cal_source'),'selected',false,'client_id','unselect'));
select pg_temp.assert_calendar(jsonb_array_length(pg_temp.calendar_call('snapshot','{}')->'items')=0,'selection removes event from all public presentation');
reset role;
select pg_temp.assert_calendar(app_private.knowledge_entity(current_setting('app.cal_owner')::uuid,'event',current_setting('app.cal_event')::uuid) is null and not exists(select 1 from jsonb_array_elements(app_private.knowledge_targets(current_setting('app.cal_owner')::uuid)) q where q->>'type'='event' and q->>'id'=current_setting('app.cal_event')),'deselected event cannot leak through Related lookup or picker');
set local role service_role;
select pg_temp.calendar_call('select',jsonb_build_object('calendar_id',current_setting('app.cal_source'),'selected',true,'client_id','select-again'));
reset role;
insert into public.captures(payload) values(jsonb_build_object('id','25000000-0000-4000-8000-000000000041','user_id',current_setting('app.cal_owner'),'client_id','note-test','type','note','title','Meeting note','content',null,'status','inbox','category_id',null,'project_id',null,'converted_task_id',null,'captured_at',now(),'organized_at',null,'archived_at',null,'deleted_at',null,'created_at',now(),'updated_at',now()));
set local role service_role;
select pg_temp.calendar_call('link',jsonb_build_object('event_id',current_setting('app.cal_event'),'capture_id','25000000-0000-4000-8000-000000000041','client_id','link-note'));
select pg_temp.calendar_error($q$select pg_temp.calendar_call('link',jsonb_build_object('event_id',current_setting('app.cal_event'),'capture_id','25000000-0000-4000-8000-000000000042','client_id','foreign-note'))$q$,'23503');
select set_config('app.cal_reset_run',(pg_temp.calendar_call('run',jsonb_build_object('account_id',current_setting('app.cal_account'),'client_id','reset-one','window',jsonb_build_object('start_day','2026-10-01','end_day','2026-11-01')))->>'id'),true);
select pg_temp.calendar_call('reset_cursor',jsonb_build_object('account_id',current_setting('app.cal_account'),'revision','3','calendar_id',current_setting('app.cal_source'),'run_id',current_setting('app.cal_reset_run')));
select pg_temp.assert_calendar(jsonb_array_length(pg_temp.calendar_call('snapshot','{}')->'items')=0,'410 reset wipes cache immediately');
select pg_temp.calendar_call('commit_events',jsonb_build_object('account_id',current_setting('app.cal_account'),'revision','4','calendar_id',current_setting('app.cal_source'),'run_id',current_setting('app.cal_reset_run'),'window',jsonb_build_object('start_day','2026-10-01','end_day','2026-11-01'),'reset',true,'sync_token','new-inert-cursor','events',jsonb_build_array(jsonb_build_object('google_id','inert-event','cancelled',false,'title','Private meeting canary','starts_at','2026-10-09T03:00:00Z','ends_at','2026-10-12T03:00:00Z','all_day',true,'location',null,'html_link',null,'reminder_minutes',null))));
select pg_temp.assert_calendar(pg_temp.calendar_call('snapshot','{}')->'items'->0->>'id'=current_setting('app.cal_event') and pg_temp.calendar_call('snapshot','{}')->'items'->0->>'linked_capture_id'='25000000-0000-4000-8000-000000000041','stable event deep link and manual note preserved after 410');
select pg_temp.calendar_call('finish_run',jsonb_build_object('run_id',current_setting('app.cal_reset_run'),'status','complete','calendar_count',1,'event_count',1));
select pg_temp.calendar_error($q$select pg_temp.calendar_call('save_tokens',jsonb_build_object('account_id',current_setting('app.cal_account'),'revision','0','tokens','{}','scopes','[]','credential_version',2))$q$,'40001');
reset role;
update public.user_roles set role='master' where user_id=current_setting('app.cal_other')::uuid;
set local role service_role;
select pg_temp.assert_calendar(not (public.google_calendar_admin_runs(current_setting('app.cal_other')::uuid,current_setting('app.cal_other_session')::uuid)::text ~ '(Private|email|token|cipher|inert)'),'master receives execution metadata only');
select pg_temp.calendar_call('reauthorize',jsonb_build_object('account_id',current_setting('app.cal_account'),'revision','5'));
reset role;
select pg_temp.assert_calendar(app_private.knowledge_entity(current_setting('app.cal_owner')::uuid,'event',current_setting('app.cal_event')::uuid) is null and not exists(select 1 from jsonb_array_elements(app_private.knowledge_targets(current_setting('app.cal_owner')::uuid)) q where q->>'type'='event' and q->>'id'=current_setting('app.cal_event')),'reauthorization fence also covers Related');
set local role service_role;
select pg_temp.calendar_call('disconnect',jsonb_build_object('account_id',current_setting('app.cal_account'),'client_id','disconnect-one'));
select pg_temp.assert_calendar(jsonb_array_length(pg_temp.calendar_call('snapshot','{}')->'items')=0 and jsonb_array_length(pg_temp.calendar_call('snapshot','{}')->'calendars')=0,'disconnect hides content before remote revocation');
select pg_temp.calendar_error($q$select pg_temp.calendar_call('commit_events',jsonb_build_object('account_id',current_setting('app.cal_account'),'revision','5'))$q$,'40001');
select pg_temp.calendar_call('finish_disconnect',jsonb_build_object('account_id',current_setting('app.cal_account'),'revision','7','client_id','disconnect-one'));
select pg_temp.assert_calendar(pg_temp.calendar_call('disconnect',jsonb_build_object('account_id',current_setting('app.cal_account'),'client_id','disconnect-one')) is null,'completed disconnect receipt prevents another remote revoke');
reset role;
select pg_temp.assert_calendar(not exists(select 1 from app_private.google_credentials) and not exists(select 1 from public.calendar_events) and not exists(select 1 from app_private.google_calendar_cursors) and not exists(select 1 from app_private.google_event_links),'disconnect removes all secrets/event cache/cursors/note links');
update public.user_entitlements set allowed=false where user_id=current_setting('app.cal_owner')::uuid and feature_key='calendario';
insert into public.user_entitlements(user_id,feature_key,allowed) values(current_setting('app.cal_owner')::uuid,'calendario',false) on conflict(user_id,feature_key) do update set allowed=false;
set local role service_role;
select pg_temp.calendar_error($q$select pg_temp.calendar_call('snapshot','{}')$q$,'42501');
reset role;
select pg_temp.assert_calendar(not exists(select 1 from public.domain_events where entity_type like 'calendar_%' and (coalesce(before,'{}')::text||coalesce(after,'{}')::text) ~ '(Private|ciphertext|refresh_token|access_token|email|google_sub|inert-cursor)'),'domain events contain metadata only');
rollback;
