import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import ts from "typescript";
const read = (path: string) => readFileSync(new URL(`../../${path}`, import.meta.url), "utf8");
function exportedFunction(path: string, name: string) { const source = ts.createSourceFile(path, read(path), ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX); const node = source.statements.find(statement => ts.isFunctionDeclaration(statement) && statement.name?.text === name); if (!node || !ts.isFunctionDeclaration(node) || !node.body) throw new Error(`Missing ${name}`); return { source, statements: node.body.statements }; }
describe("Admin boundary scan", () => {
 it.each(["GET", "POST"])("%s begins with requireMaster before parsing, replay or SDK", name => { const { source, statements } = exportedFunction("src/app/api/admin/route.ts", name), first = statements[0]; expect(first && ts.isTryStatement(first)).toBe(true); if (!first || !ts.isTryStatement(first)) throw new Error("expected try"); expect(first.tryBlock.statements[0]?.getText(source)).toBe("const actor = await requireMaster();"); });
 it("pure executor begins with master guard and page revalidates per navigation", () => { const executor = exportedFunction("src/core/admin/index.ts", "executeAdminCommand"); expect(executor.statements[0]?.getText(executor.source)).toBe("await port.requireMaster();"); const page = exportedFunction("src/app/(workspace)/admin/page.tsx", "Page"); expect(page.statements[0]?.getText(page.source)).toContain("await requireMaster()"); });
 it("browser owns only transient credential form and private same-origin fetch", () => { const source = read("src/components/features/admin/admin-workspace.tsx"); expect(source).not.toMatch(/localStorage|sessionStorage|indexedDB|executeDomainCommand|@supabase|adapters\/db|console\./); expect(source).toContain('credentials: "same-origin"'); expect(source).toContain('redirect: "error"'); expect(source).toContain('"X-Expected-User-ID": userId'); expect(source).toContain('setPassword("")'); expect(source).toContain("DEMO_LOGOUT_EVENT"); });
 it("SQL never reads personal module tables or domain-event contents", () => { const sql = read("supabase/migrations/20261009150122_identity_admin_settings.sql"); expect(sql).not.toMatch(/\b(from|join)\s+public\.(captures|tasks|knowledge_|finance_|drive_|vault_|projects|habits|domain_events)/i); expect(sql).toContain("second-brain:usable-masters"); expect(sql).toContain("delete from auth.sessions where user_id=op.target_user_id"); expect(sql).toContain("delete from auth.refresh_tokens where user_id::text=op.target_user_id::text"); expect(sql).toContain("not m.must_change_password"); expect(sql).toContain("not exists(select 1 from public.user_entitlements where user_id=u.id and feature_key='admin' and not allowed)"); });
 it("versioned SQL specifies service-only RPCs, exact creation marker and credential-free receipts", () => { const sql = read("supabase/migrations/20261009150122_identity_admin_settings.sql"); expect(sql).toContain("revoke all on app_private.admin_operations,public.admin_audit_events from public,anon,authenticated,service_role"); expect(sql).toContain("new.raw_app_meta_data->>'sc_admin_operation' is distinct from op.operation_id::text"); expect(sql).toContain("jsonb_build_object('commitment',op.commitment)"); expect(sql).not.toMatch(/encrypted_password|temporary_password|password\s+(text|varchar)|email\s+(text|varchar)/i); });
 it("private execution claim cannot expire or appear in public DTO/journal", () => { const sql = read("supabase/migrations/20261009150122_identity_admin_settings.sql"); const dto = sql.slice(sql.indexOf("create function app_private.admin_operation_json"), sql.indexOf("create function app_private.admin_audit")); expect(dto).not.toContain("active_execution"); expect(dto).not.toContain("commitment"); expect(sql).toContain("p_phase='needs_reconciliation' and p_release is true"); expect(sql).not.toMatch(/active_execution[^;]*(interval|expires|expiration|ttl)/i); expect(read("src/lib/demo/client-command-specs.ts")).not.toContain("admin.user.create"); });
});
