import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
const read = (path: string) => readFileSync(new URL(`../../${path}`, import.meta.url), "utf8");
describe("Calendar shared and server boundaries", () => {
 it("browser has no SDK/secrets/storage and fences OAuth redirects on logout", () => { const ui = read("src/components/features/calendario/calendar-workspace.tsx"); expect(ui).not.toMatch(/@supabase|adapters\/db|localStorage|sessionStorage|indexedDB|refresh_token|access_token|code_verifier|ciphertext/); expect(ui).toContain('executeDomainCommand(command'); expect(ui).toContain('await refreshActive()'); expect(ui).toContain('type="event"'); expect(ui).toContain('rel="noopener noreferrer"'); expect(ui).toContain("DEMO_LOGOUT_EVENT"); expect(ui).toContain("signal: controller.signal"); expect(ui).toContain("if (!alive()) return"); expect(ui).toContain('result.code === "SESSION_CHANGED"'); });
 it("reminders cannot read hidden/vetoed agenda and clear on logout", () => { const source = read("src/components/layout/calendar-meeting-reminders.tsx"); expect(source).toContain("access.allowed && access.visible"); expect(source).toContain('useDemoQuery("agenda", enabled)'); expect(source).toContain("meeting_reminders_enabled"); expect(source).toContain("DEMO_LOGOUT_EVENT"); expect(source).not.toMatch(/localStorage|sessionStorage|Notification\.requestPermission/); });
 it("core has no credentials SDK or I/O", () => { expect(read("src/core/calendario/service.ts")).not.toMatch(/fetch\(|process\.env|node:crypto|@supabase|next\/|server-only/); });
 it("migration preserves existing closed types and exact in-flight claim", () => { const sql = read("supabase/migrations/20261009160158_google_calendar.sql"); expect(sql).toContain("conname='domain_events_entity_type_check'"); expect(sql).toContain("calendar_metadata_only"); expect(sql).toContain("execution_row.execution=p_execution"); expect(sql).toContain("x.execution is not null and x.execution<>p_execution"); expect(sql).toContain("a.status<>'connected'"); expect(sql).toContain("s.selected and a.status='connected'"); expect(sql).not.toMatch(/execution[^;]*(expires|ttl|interval)/i); });
 it("Admin independently queries metadata and aborts on owner logout or retry", () => { const source = read("src/components/features/admin/calendar-admin-runs.tsx"); expect(source).toContain("/api/calendar/admin-runs"); expect(source).toContain("state.controller?.abort()"); expect(source).toContain("DEMO_LOGOUT_EVENT"); expect(source).toContain("detail.userId === app.userId"); expect(source).toContain("if (!alive()) return"); expect(source).toContain("setRuns([])"); expect(source).not.toMatch(/features\/calendario|run\.(email|title|content)|refresh_token/); });
});
