import { beforeEach, describe, expect, it, vi } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
const seams = vi.hoisted(() => ({ mode: "connected", view: "month", policy: { entitlements: {}, preferences: {}, isAdmin: false }, data: {} as unknown }));
vi.mock("next/navigation", () => ({ useRouter: () => ({ replace: vi.fn() }), useSearchParams: () => new URLSearchParams({ date: "2026-10-10", view: seams.view }) }));
vi.mock("../../src/lib/demo/demo-provider", () => ({ useDemoApplication: () => ({ mode: seams.mode, userId: "25000000-0000-4000-8000-000000000001", today: () => "2026-10-09", executeDomainCommand: vi.fn(), refreshActive: vi.fn(), commands: { captures: { create: vi.fn() } } }), useDemoQuery: (key: string) => ({ status: "ready", data: key === "agenda" ? seams.data : { items: [] }, retry: vi.fn() }) }));
vi.mock("../../src/lib/navigation/demo-access-provider", () => ({ useDemoAccess: () => ({ policy: seams.policy }) }));
vi.mock("../../src/components/layout/related-panel", () => ({ RelatedPanel: () => null }));
import { CalendarWorkspace } from "../../src/components/features/calendario/calendar-workspace";
const owner = "25000000-0000-4000-8000-000000000001", account = "25000000-0000-4000-8000-000000000002", source = "25000000-0000-4000-8000-000000000003";
beforeEach(() => { seams.mode = "connected"; seams.view = "month"; seams.data = { accounts: [{ id: account, user_id: owner, email: "calendar@example.invalid", status: "connected", scopes: [], last_synced_at: null }], calendars: [{ id: source, account_id: account, user_id: owner, name: "Equipe", color_key: "calendar", selected: true }], items: [{ id: "event", title: "Retiro de três dias", starts_at: "2026-10-09T03:00:00Z", ends_at: "2026-10-12T03:00:00Z", all_day: true, location: null, linked_capture_id: null, habit_id: null }], preferences: { default_calendar_view: "month", meeting_reminders_enabled: true, meeting_reminder_minutes: 10 }, window: { start_day: "2026-10-01", end_day: "2026-11-01" } }; });
describe("Calendar actual static UI, no browser or OAuth transport", () => {
 it("connected controls expose real accounts, sources and reading-only status", () => { const html = renderToStaticMarkup(<CalendarWorkspace />); expect(html).toContain("calendar@example.invalid"); expect(html).toContain("Conectar Google"); expect(html).toContain("Sincronizar período"); expect(html).toContain('role="switch"'); expect(html).toContain('aria-checked="true"'); expect(html).toContain("Agenda Google em modo de leitura"); expect(html).not.toContain("Agenda de exemplo"); });
 it.each(["month", "week", "day"])("three-day event appears on %s view without false exclusive-end day", view => { seams.view = view; const html = renderToStaticMarkup(<CalendarWorkspace />); expect(html).toContain("Retiro de três dias"); expect(html).toContain("Dia inteiro"); if (view === "month") { expect(html).toContain('aria-label="Mês em lista"'); expect(html.match(/Retiro de três dias/g)).toHaveLength(6); } });
 it("demo never offers external OAuth or disconnect controls", () => { seams.mode = "demo"; const html = renderToStaticMarkup(<CalendarWorkspace />); expect(html).toContain("Agenda de exemplo"); expect(html).not.toContain("Conectar Google"); expect(html).not.toContain("Desconectar"); });
});
