import { describe, expect, it, vi } from "vitest";
import { createKnowledgeClient } from "../../src/components/features/conhecimento/knowledge-client";
const actor = "10000000-0000-4000-8000-000000000001";
describe("Conhecimento client channel", () => {
  it("usa cookie-only e conta esperada para leitura/escrita", async () => { const fetcher = vi.fn<typeof fetch>(async () => Response.json({ ok: true, result: { id: actor } })); await createKnowledgeClient(actor, fetcher).command({ command: "knowledge.notebook.create", input: { name: "Nome", client_id: "stable" } }); expect(fetcher).toHaveBeenCalledWith("/api/knowledge", expect.objectContaining({ credentials: "same-origin", headers: { "X-Expected-User-ID": actor, "Content-Type": "application/json" } })); expect(JSON.stringify(fetcher.mock.calls)).not.toMatch(/authorization|jwt|secret_key/i); });
  it("falha de rede mantém resultado incerto e não vira sucesso", async () => { const fetcher = vi.fn<typeof fetch>(async () => { throw new Error("offline"); }); await expect(createKnowledgeClient(actor, fetcher).command({ command: "knowledge.notebook.create", input: { name: "Nome", client_id: "stable" } })).rejects.toMatchObject({ code: "COMMIT_UNKNOWN", unknownOutcome: true }); });
  it("recusa resposta de outra conta", async () => { const fetcher = vi.fn<typeof fetch>(async () => Response.json({ revision: "0", notebooks: [{ user_id: "other", id: actor }], pages: [], refs: [], links: [], targets: [] })); await expect(createKnowledgeClient(actor, fetcher).load()).rejects.toMatchObject({ code: "SESSION_CHANGED" }); });
  it("escrita conectada usa o sender compartilhado e preserva resultado incerto", async () => { const fetcher = vi.fn<typeof fetch>(), sender = vi.fn(async () => { throw { code: "COMMIT_UNKNOWN", message: "Envio pendente", outcomeUnknown: true }; }); const request = { command: "knowledge.notebook.create" as const, input: { name: "Nome", client_id: "stable" } }; await expect(createKnowledgeClient(actor, fetcher, sender).command(request)).rejects.toMatchObject({ unknownOutcome: true }); expect(sender).toHaveBeenCalledWith(request.command, request.input); expect(fetcher).not.toHaveBeenCalled(); });
});
