import { beforeEach, describe, expect, it, vi } from "vitest";
import type { AuthenticatedIdentity } from "../../src/lib/auth/types";
const mocks = vi.hoisted(() => ({ config: vi.fn(), services: vi.fn(), identity: vi.fn(), flow: vi.fn(), redirect: vi.fn((path: string) => { throw new Error(`redirect:${path}`); }) }));
vi.mock("server-only", () => ({}));
vi.mock("next/navigation", () => ({ redirect: mocks.redirect }));
vi.mock("../../src/lib/auth/config", () => ({ readAuthConfiguration: mocks.config }));
vi.mock("../../src/lib/auth/runtime", () => ({ requestAuthServices: mocks.services }));
import { getAuthFormAvailability, getPasswordFormContext, readAuthState, requireFeature, requireMaster, requireUser } from "../../src/lib/auth/guards";
const identity: AuthenticatedIdentity = { userId: "user-a", sessionId: "session-a", mustChangePassword: false, role: "user", entitlements: {} };
beforeEach(() => { vi.resetAllMocks(); mocks.config.mockReturnValue({ mode: "supabase" }); mocks.identity.mockResolvedValue(identity); mocks.flow.mockReturnValue(null); mocks.services.mockResolvedValue({ gateway: { readIdentity: mocks.identity }, flows: { get: mocks.flow } }); });
describe("guards keep authentication independent of UI visibility", () => {
  it("demo reads no SDK and never supplies a fake authenticated user", async () => { mocks.config.mockReturnValue({ mode: "demo" }); expect(await readAuthState()).toEqual({ mode: "demo" }); await expect(requireUser()).rejects.toMatchObject({ code: "demo" }); expect(mocks.services).not.toHaveBeenCalled(); expect(await getAuthFormAvailability()).toBe(false); });
  it("bad real configuration is unavailable, without pretending demo identity", async () => { mocks.config.mockImplementation(() => { throw new Error("configuration"); }); expect(await getAuthFormAvailability()).toBe(false); await expect(readAuthState()).rejects.toThrow("configuration"); expect(mocks.services).not.toHaveBeenCalled(); });
  it("missing current identity redirects to sign in", async () => { mocks.identity.mockResolvedValue(null); await expect(requireUser()).rejects.toThrow("redirect:/entrar?notice=session-required"); });
  it("provisional password redirects normal operations but permits the dedicated form", async () => { mocks.identity.mockResolvedValue({ ...identity, mustChangePassword: true }); await expect(requireUser()).rejects.toThrow("redirect:/trocar-senha"); expect(await requireUser({ allowPasswordChange: true })).toMatchObject({ mustChangePassword: true }); expect(await getPasswordFormContext()).toMatchObject({ requiresCurrentPassword: true }); });
  it("veto beats master and every master operation has the same guard", async () => { await expect(requireMaster()).rejects.toMatchObject({ code: "forbidden" }); mocks.identity.mockResolvedValue({ ...identity, role: "master", entitlements: { admin: false, drive: false } }); await expect(requireMaster()).rejects.toMatchObject({ code: "forbidden" }); await expect(requireFeature("drive")).rejects.toMatchObject({ code: "forbidden" }); });
  it("recovery form requires a signed proof for this exact session", async () => { await expect(getPasswordFormContext("recovery")).rejects.toThrow("recovery-invalid"); mocks.flow.mockImplementation((kind) => kind === "recovery-session" ? { kind, userId: identity.userId, sessionId: identity.sessionId } : null); expect(await getPasswordFormContext("recovery")).toEqual({ available: true, requiresCurrentPassword: false, completionPending: false }); });
  it("reload retains pending UI only for current user's session checkpoint", async () => { mocks.flow.mockImplementation((kind) => kind === "password-updated" ? { kind, userId: identity.userId, sessionId: identity.sessionId } : null); expect(await getPasswordFormContext("recovery")).toMatchObject({ completionPending: true, requiresCurrentPassword: false }); mocks.flow.mockImplementation((kind) => kind === "password-updated" ? { kind, userId: "other", sessionId: identity.sessionId } : null); await expect(getPasswordFormContext("recovery")).rejects.toThrow("recovery-invalid"); });
});
