import { describe, expect, it, vi } from "vitest";
import type { AuthFlow } from "../../src/lib/auth/flow-state";
import { subjectHash } from "../../src/lib/auth/flow-state";
import type { AuthServices } from "../../src/lib/auth/ports";
import type { AuthenticatedIdentity } from "../../src/lib/auth/types";
import { exchangeRecovery, recoverPassword, signIn, updatePassword } from "../../src/lib/auth/service";

const identity: AuthenticatedIdentity = { userId: "user-a", sessionId: "session-a", email: "a@example.invalid", mustChangePassword: false, role: "user", entitlements: {} };
function fixture() {
  const events: string[] = [], flows = new Map<string, AuthFlow>();
  const services: AuthServices = {
    appOrigin: "https://app.example.invalid", stateSecret: "state".repeat(8), now: () => 1000, randomId: () => "12345678-0000-4000-8000-123456789012",
    flows: { get: (kind) => flows.get(kind) ?? null, put(flow) { flows.set(flow.kind, flow); events.push(`flow:${flow.kind}`); }, clear(kind) { flows.delete(kind); }, clearSessionCookies() { flows.clear(); events.push("clear"); } },
    gateway: {
      readIdentity: vi.fn(async () => { events.push("identity"); return structuredClone(identity); }),
      signIn: vi.fn(async () => { events.push("signin"); return true; }),
      requestRecovery: vi.fn(async () => { events.push("email"); }),
      exchangeCode: vi.fn(async () => { events.push("exchange"); return true; }),
      updatePassword: vi.fn(async () => { events.push("password"); return true; }),
      signOut: vi.fn(async (scope) => { events.push(`logout:${scope}`); return true; }),
      completePasswordChange: vi.fn(async () => { events.push("complete"); }),
    },
    limit: vi.fn(async () => { events.push("limit"); return { allowed: true, retryAfterSeconds: 0 }; }),
  };
  return { services, events, flows };
}
const password = { password: "Nova senha correta!", confirmPassword: "Nova senha correta!", currentPassword: "Atual senha correta!" };
describe("authentication service without a provider/network", () => {
  it("limits before sign in and resolves only a safe return URL", async () => { const f = fixture(); expect(await signIn(f.services, { email: " A@example.invalid ", password: "old", returnTo: "//evil.test" })).toEqual({ redirectTo: "/" }); expect(f.events).toEqual(["limit", "signin", "identity"]); expect(f.services.limit).toHaveBeenCalledWith("login", "a@example.invalid"); });
  it("redirects provisional password only after current access DTO", async () => { const f = fixture(); vi.mocked(f.services.gateway.readIdentity).mockResolvedValue({ ...identity, mustChangePassword: true }); expect(await signIn(f.services, { email: "a@example.invalid", password: "old" })).toEqual({ redirectTo: "/trocar-senha" }); });
  it("rejects the sixth attempt before credentials reach provider", async () => { const f = fixture(); vi.mocked(f.services.limit).mockResolvedValue({ allowed: false, retryAfterSeconds: 42 }); expect(await signIn(f.services, { email: "a@example.invalid", password: "old" })).toMatchObject({ state: { status: "error", retryAfterSeconds: 42 } }); expect(f.services.gateway.signIn).not.toHaveBeenCalled(); });
  it("limiter failure never becomes unlimited authentication", async () => { const f = fixture(); vi.mocked(f.services.limit).mockRejectedValue(new Error("unavailable")); await expect(signIn(f.services, { email: "a@example.invalid", password: "old" })).rejects.toThrow(); expect(f.services.gateway.signIn).not.toHaveBeenCalled(); });
  it("clears newly issued cookies when persisted access rejects login", async () => { const f = fixture(); vi.mocked(f.services.gateway.readIdentity).mockResolvedValue(null); expect(await signIn(f.services, { email: "a@example.invalid", password: "old" })).toMatchObject({ state: { status: "error" } }); expect(f.events).toContain("logout:local"); expect(f.events.at(-1)).toBe("clear"); });
  it("recovery gives identical public result for accepted and rejected account", async () => { const f = fixture(), other = fixture(); vi.mocked(other.services.gateway.requestRecovery).mockRejectedValue(new Error("account/email details")); const a = await recoverPassword(f.services, { email: "a@example.invalid" }); const b = await recoverPassword(other.services, { email: "a@example.invalid" }); expect(a).toEqual(b); expect(JSON.stringify(b)).not.toContain("account/email details"); expect(f.flows.get("recovery-request")).not.toHaveProperty("email"); });
  it("invalid callback cannot exchange code or erase a legitimate pending flow", async () => { const f = fixture(); await recoverPassword(f.services, { email: "a@example.invalid" }); expect(await exchangeRecovery(f.services, { code: "code", state: "wrong" })).toContain("recovery-invalid"); expect(f.services.gateway.exchangeCode).not.toHaveBeenCalled(); expect(f.flows.has("recovery-request")).toBe(true); });
  it("valid PKCE callback binds recovery to verified user and session, then consumes request", async () => { const f = fixture(); await recoverPassword(f.services, { email: "a@example.invalid" }); expect(await exchangeRecovery(f.services, { code: "code", state: f.services.randomId(), flowId: "flow-id" })).toBe("/redefinir-senha"); expect(f.flows.get("recovery-session")).toMatchObject({ userId: identity.userId, sessionId: identity.sessionId }); expect(f.flows.has("recovery-request")).toBe(false); expect(await exchangeRecovery(f.services, { code: "code", state: f.services.randomId() })).toContain("recovery-invalid"); });
  it("PKCE exchange for another email is rejected and its session cleared", async () => { const f = fixture(); await recoverPassword(f.services, { email: "other@example.invalid" }); expect(await exchangeRecovery(f.services, { code: "code", state: f.services.randomId() })).toContain("recovery-invalid"); expect(f.events.at(-1)).toBe("clear"); });
  it("normal change reauthenticates, passes current password and orders completion", async () => { const f = fixture(); expect(await updatePassword(f.services, password)).toEqual({ redirectTo: "/entrar?notice=password-updated" }); expect(f.services.gateway.updatePassword).toHaveBeenCalledWith(password.password, password.currentPassword); expect(f.events).toEqual(["identity", "limit", "limit", "signin", "identity", "password", "identity", "flow:password-updated", "logout:others", "complete", "logout:global", "clear"]); });
  it("sixth credential attempt is also refused during password reauthentication", async () => { const f = fixture(); vi.mocked(f.services.limit).mockResolvedValueOnce({ allowed: true, retryAfterSeconds: 0 }).mockResolvedValueOnce({ allowed: false, retryAfterSeconds: 40 }); expect(await updatePassword(f.services, password)).toMatchObject({ state: { retryAfterSeconds: 40, completionPending: false } }); expect(f.services.limit).toHaveBeenNthCalledWith(2, "login", identity.email); expect(f.services.gateway.signIn).not.toHaveBeenCalled(); expect(f.services.gateway.updatePassword).not.toHaveBeenCalled(); });
  it("provisional password still supplies current_password to the native Auth setting", async () => { const f = fixture(); vi.mocked(f.services.gateway.readIdentity).mockResolvedValue({ ...identity, mustChangePassword: true }); await updatePassword(f.services, { ...password, currentPassword: "" }); expect(f.services.gateway.updatePassword).not.toHaveBeenCalled(); });
  it("recovery proof allows change without current password only for the same session", async () => {
    const f = fixture(); f.flows.set("recovery-session", { kind: "recovery-session", userId: identity.userId, sessionId: identity.sessionId, expiresAt: 99999 }); await updatePassword(f.services, { ...password, currentPassword: "" }); expect(f.services.gateway.signIn).not.toHaveBeenCalled(); expect(f.services.gateway.updatePassword).toHaveBeenCalledWith(password.password, undefined);
    const other = fixture(); other.flows.set("recovery-session", { kind: "recovery-session", userId: identity.userId, sessionId: "different", expiresAt: 99999 }); await updatePassword(other.services, { ...password, currentPassword: "" }); expect(other.services.gateway.updatePassword).not.toHaveBeenCalled();
  });
  it("failed password update emits no completion and retains no checkpoint", async () => { const f = fixture(); vi.mocked(f.services.gateway.updatePassword).mockResolvedValue(false); await updatePassword(f.services, password); expect(f.services.gateway.completePasswordChange).not.toHaveBeenCalled(); expect(f.flows.has("password-updated")).toBe(false); });
  it("lost identity after password change sends user to sign in with the new password", async () => { const f = fixture(); vi.mocked(f.services.gateway.readIdentity).mockResolvedValueOnce(identity).mockResolvedValueOnce(identity).mockRejectedValueOnce(new Error("network")); expect(await updatePassword(f.services, password)).toEqual({ redirectTo: "/entrar?notice=password-recheck" }); expect(f.events.at(-1)).toBe("clear"); expect(f.services.gateway.completePasswordChange).not.toHaveBeenCalled(); });
  it("retries a partial completion without password, reauthentication or new password write", async () => {
    const f = fixture(); vi.mocked(f.services.gateway.completePasswordChange).mockRejectedValueOnce(new Error("db")); expect(await updatePassword(f.services, password)).toMatchObject({ state: { completionPending: true } }); const checkpoint = f.flows.get("password-updated"); expect(JSON.stringify(checkpoint)).not.toContain(password.password); expect(await updatePassword(f.services, { password: "", confirmPassword: "", currentPassword: "" })).toEqual({ redirectTo: "/entrar?notice=password-updated" }); expect(f.services.gateway.updatePassword).toHaveBeenCalledTimes(1); expect(f.services.gateway.signIn).toHaveBeenCalledTimes(1); expect(f.services.gateway.completePasswordChange).toHaveBeenCalledTimes(2); expect(vi.mocked(f.services.gateway.completePasswordChange).mock.calls[0]?.[1]).toBe(vi.mocked(f.services.gateway.completePasswordChange).mock.calls[1]?.[1]);
  });
  it("does not clear the flag before revocation of other sessions succeeds", async () => { const f = fixture(); vi.mocked(f.services.gateway.signOut).mockResolvedValueOnce(false); expect(await updatePassword(f.services, password)).toMatchObject({ state: { completionPending: true } }); expect(f.services.gateway.completePasswordChange).not.toHaveBeenCalled(); });
  it("retains pending completion across limiter rejection/failure", async () => { const f = fixture(); vi.mocked(f.services.gateway.completePasswordChange).mockRejectedValueOnce(new Error("db")); await updatePassword(f.services, password); vi.mocked(f.services.limit).mockResolvedValueOnce({ allowed: false, retryAfterSeconds: 5 }); expect(await updatePassword(f.services, { password: "", confirmPassword: "", currentPassword: "" })).toMatchObject({ state: { completionPending: true, retryAfterSeconds: 5 } }); vi.mocked(f.services.limit).mockRejectedValueOnce(new Error("offline")); expect(await updatePassword(f.services, { password: "", confirmPassword: "", currentPassword: "" })).toMatchObject({ state: { completionPending: true } }); });
  it("final logout failure cannot promise a retry with cookies removed by the SDK", async () => { const f = fixture(); vi.mocked(f.services.gateway.signOut).mockResolvedValueOnce(true).mockResolvedValueOnce(false); expect(await updatePassword(f.services, password)).toEqual({ redirectTo: "/entrar?notice=password-updated-logout-incomplete" }); expect(f.events.at(-1)).toBe("clear"); expect(f.flows.has("password-updated")).toBe(false); });
  it("does not accept another user's completion checkpoint", async () => { const f = fixture(); f.flows.set("password-updated", { kind: "password-updated", userId: "other", sessionId: identity.sessionId, clientId: "other", expiresAt: 99999 }); await updatePassword(f.services, { password: "", confirmPassword: "", currentPassword: "" }); expect(f.services.gateway.completePasswordChange).not.toHaveBeenCalled(); });
  it("does not update on mismatching confirmation or excessive UTF8 size", async () => { const f = fixture(); await updatePassword(f.services, { ...password, confirmPassword: "wrong" }); await updatePassword(f.services, { ...password, password: "🙂".repeat(19), confirmPassword: "🙂".repeat(19) }); expect(f.services.gateway.updatePassword).not.toHaveBeenCalled(); });
  it("stores only an HMAC of recovery email", async () => { const f = fixture(); await recoverPassword(f.services, { email: "a@example.invalid" }); expect(f.flows.get("recovery-request")).toMatchObject({ subject: subjectHash(f.services.stateSecret, "recovery-email", "a@example.invalid") }); });
});
