import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { driveDTO,executarDrive,type ComandoDrive } from "@/core/drive";
import { exigir } from "@/core/contracts/base";
import { assertFeature } from "@/lib/auth/policy";
import { authorizeFilesRequest,fileHeaders,fileObject,fileUuid,filesFailure,readFilesBody } from "@/adapters/db/files-http";
import { filesServicesForRequest } from "@/adapters/db/files-runtime";
import { createDriveStore } from "@/adapters/db/files-store";
export const runtime="nodejs";export const dynamic="force-dynamic";
const fields:Record<ComandoDrive["command"],string[]>={"drive.folder.create":["name","parent_id","project_id"],"drive.folder.update":["id","name"],"drive.folder.move":["id","parent_id"],"drive.folder.delete":["id"],"drive.folder.restore":["id"],"drive.file.update":["id","name"],"drive.file.move":["id","folder_id"],"drive.file.delete":["id"],"drive.file.restore":["id"],"drive.file.star":["id","starred"]};
export async function GET(request:Request){const headers=fileHeaders();try{const{config,actor}=await authorizeFilesRequest(request,headers);assertFeature(actor,"drive");const services=filesServicesForRequest(config,actor),state=await createDriveStore(services.gateway("read.drive")).snapshot();return NextResponse.json(driveDTO(state),{headers});}catch(error){return filesFailure(error,headers);}}
export async function POST(request:Request){const headers=fileHeaders();try{const{config,actor}=await authorizeFilesRequest(request,headers,true);const value=await readFilesBody(request);exigir(fileObject(value)&&Object.keys(value).every(key=>["command","input"].includes(key))&&typeof value.command==="string"&&fileObject(value.input),"Comando inválido.");const input=value.input;exigir(typeof input.client_id==="string"&&input.client_id.trim().length>0&&input.client_id.length<=200,"Informe client_id.");let result:unknown;
 if(value.command==="file.upload.finalize"){exigir(Object.keys(input).every(key=>["upload_id","client_id"].includes(key))&&fileUuid(input.upload_id),"Envio inválido.");result=await filesServicesForRequest(config,actor).finalize(input.upload_id,input.client_id);}
 else if(value.command==="avatar.set"||value.command==="avatar.remove"){assertFeature(actor,"configuracoes");exigir(Object.keys(input).every(key=>(value.command==="avatar.remove"?["client_id"]:["file_id","client_id"]).includes(key))&&(value.command==="avatar.remove"||fileUuid(input.file_id)),"Avatar inválido.");result=await filesServicesForRequest(config,actor).avatar(value.command==="avatar.remove"?null:input.file_id as string,input.client_id);}
 else{assertFeature(actor,"drive");exigir(Object.hasOwn(fields,value.command)&&Object.keys(input).every(key=>["client_id",...fields[value.command as ComandoDrive["command"]]].includes(key)),"Campos não permitidos.");for(const key of ["id","parent_id","folder_id","project_id"])if(input[key]!==undefined&&input[key]!==null)exigir(fileUuid(input[key]),"Identificador inválido.");if(value.command!=="drive.folder.create")exigir(fileUuid(input.id),"Informe o registro.");const requestValue=value as unknown as ComandoDrive;result=await executarDrive(createDriveStore(filesServicesForRequest(config,actor).gateway(value.command)),{clock:{now:()=>new Date().toISOString()},ids:{next:randomUUID}},{user_id:actor.userId,canal:"web"},requestValue);}
 return NextResponse.json({ok:true,result},{headers});}catch(error){return filesFailure(error,headers);}}
