import { describe, expect, it, vi } from "vitest";
import { AdminAuthUncertainError, decodeAdminCommand, executeAdminCommand, preserveUsableMaster, usableMaster, type AdminAction, type AdminAuthPort, type AdminMasterEligibility, type AdminOperation, type AdminPort } from "../../src/core/admin";
const actor = "10000000-0000-4000-8000-000000000001", target = "10000000-0000-4000-8000-000000000002", opId = "10000000-0000-4000-8000-000000000003";
const request = { command: "admin.user.create", input: { client_id: "original", email: "person@example.invalid", temporary_password: "Provisoria privada 123!" } } as const;
function fixture(command: AdminAction = "admin.user.create") {
 const log: string[] = []; let fence = false, sessions = 2;
 let operation: AdminOperation = { operation_id: opId, client_id: "original", actor_user_id: actor, target_user_id: target, command, phase: "reserved", role: null, feature_key: null, allowed: null, created_at: "2026-10-09T12:00:00Z", updated_at: "2026-10-09T12:00:00Z" };
 const port: AdminPort = {
  requireMaster: vi.fn(async () => { log.push("master"); }), snapshot: vi.fn(async () => ({ users: [], audit: [], operations: [] })),
  reserve: vi.fn(async () => { log.push("reserve"); fence = true; return structuredClone(operation); }),
  claim: vi.fn(async () => { log.push("claim"); return structuredClone(operation); }),
  guard: vi.fn(async () => { log.push("guard"); return structuredClone(operation); }),
  transition: vi.fn(async (_, phase) => { log.push(phase); operation = { ...operation, phase }; if (phase === "revoked") sessions = 0; return structuredClone(operation); }),
  complete: vi.fn(async () => { log.push("complete"); if (sessions) throw new Error("sessions remain"); operation = { ...operation, phase: "complete" }; fence = command === "admin.user.block"; return structuredClone(operation); }),
 };
 const auth: AdminAuthPort = { create: vi.fn(async () => { log.push("create"); }), verifyCreated: vi.fn(async () => { log.push("verify"); return true; }), ban: vi.fn(async (_, blocked) => { log.push(blocked ? "ban" : "unban"); }) };
 return { port, auth, log, get fence() { return fence; }, get sessions() { return sessions; }, setPhase(phase: AdminOperation["phase"]) { operation.phase = phase; } };
}
describe("Admin pure commands and fail-closed saga", () => {
 it("checks master before decoding input or computing a keyed commitment", async () => { const f = fixture(), commit = vi.fn(); vi.mocked(f.port.requireMaster).mockRejectedValue(new Error("forbidden")); await expect(executeAdminCommand(f.port, f.auth, commit, { invalid: true })).rejects.toThrow("forbidden"); expect(commit).not.toHaveBeenCalled(); expect(f.port.reserve).not.toHaveBeenCalled(); expect(f.auth.create).not.toHaveBeenCalled(); });
 it("persists only keyed identity; e-mail and credentials never reach the SQL port", async () => { const f = fixture(), commit = vi.fn(() => "a".repeat(64)); await executeAdminCommand(f.port, f.auth, commit, request); expect(commit).toHaveBeenCalledWith(request); expect(f.port.reserve).toHaveBeenCalledWith({ command: request.command, client_id: "original", commitment: "a".repeat(64) }); expect(JSON.stringify(vi.mocked(f.port.reserve).mock.calls)).not.toContain(request.input.email); expect(JSON.stringify(vi.mocked(f.port.reserve).mock.calls)).not.toContain(request.input.temporary_password); });
 it("reserves and fences before Auth, revokes every session before releasing creation", async () => { const f = fixture(); expect((await executeAdminCommand(f.port, f.auth, () => "a".repeat(64), request)).phase).toBe("complete"); expect(f.log).toEqual(["master", "reserve", "guard", "create", "auth_applied", "revoked", "guard", "unban", "complete"]); expect(f.sessions).toBe(0); expect(f.fence).toBe(false); });
 it("failed creation keeps the persisted fence and requests reconciliation", async () => { const f = fixture(); vi.mocked(f.auth.create).mockRejectedValue(new Error("Auth unknown response")); await expect(executeAdminCommand(f.port, f.auth, () => "a".repeat(64), request)).rejects.toThrow("Auth unknown"); expect(f.fence).toBe(true); expect(f.port.complete).not.toHaveBeenCalled(); expect(f.log.at(-1)).toBe("needs_reconciliation"); });
 it("failed unban never clears moderation or announces completion", async () => { const f = fixture(); vi.mocked(f.auth.ban).mockRejectedValue(new Error("unban unavailable")); await expect(executeAdminCommand(f.port, f.auth, () => "a".repeat(64), request)).rejects.toThrow(); expect(f.fence).toBe(true); expect(f.sessions).toBe(0); expect(f.port.complete).not.toHaveBeenCalled(); });
 it("blocking confirms ban, revokes sessions and retains the block", async () => { const f = fixture("admin.user.block"); await executeAdminCommand(f.port, f.auth, () => "b".repeat(64), { command: "admin.user.block", input: { client_id: "original", target_user_id: target } }); expect(f.log).toEqual(["master", "reserve", "guard", "ban", "auth_applied", "revoked", "complete"]); expect(f.fence).toBe(true); expect(f.sessions).toBe(0); });
 it("forcing a password fences and bans before revocation, then restores forced login", async () => { const f = fixture("admin.user.force_password"); await executeAdminCommand(f.port, f.auth, () => "c".repeat(64), { command: "admin.user.force_password", input: { client_id: "original", target_user_id: target } }); expect(f.log).toEqual(["master", "reserve", "guard", "ban", "auth_applied", "revoked", "guard", "unban", "complete"]); });
 it("unblock still revokes all old sessions before active moderation", async () => { const f = fixture("admin.user.unblock"); await executeAdminCommand(f.port, f.auth, () => "d".repeat(64), { command: "admin.user.unblock", input: { client_id: "original", target_user_id: target } }); expect(f.auth.ban).toHaveBeenCalledWith(expect.objectContaining({ target_user_id: target }), false); expect(f.log.indexOf("revoked")).toBeLessThan(f.log.indexOf("unban")); });
 it("reconciles an ambiguous creation through UUID and marker without requesting a password", async () => { const f = fixture(); f.setPhase("needs_reconciliation"); await executeAdminCommand(f.port, f.auth, () => { throw new Error("must not store reconciliation payload"); }, { command: "admin.operation.reconcile", input: { client_id: "resume", operation_id: opId } }); expect(f.port.reserve).not.toHaveBeenCalled(); expect(f.auth.create).not.toHaveBeenCalled(); expect(f.auth.verifyCreated).toHaveBeenCalled(); expect(f.port.complete).toHaveBeenCalled(); });
 it("missing Auth creation stays pending and needs the original transient credentials", async () => { const f = fixture(); vi.mocked(f.auth.verifyCreated).mockResolvedValue(false); await expect(executeAdminCommand(f.port, f.auth, () => "unused", { command: "admin.operation.reconcile", input: { client_id: "resume", operation_id: opId } })).rejects.toThrow("envio original"); expect(f.auth.create).not.toHaveBeenCalled(); expect(f.port.complete).not.toHaveBeenCalled(); expect(f.log.at(-1)).toBe("needs_reconciliation"); });
 it.each(["admin.user.role", "admin.user.entitlement"] as const)("%s completes in one SQL transaction without Auth SDK", async command => { const f = fixture(command); f.setPhase("complete"); const value = command === "admin.user.role" ? { command, input: { client_id: "original", target_user_id: target, role: "master" } } : { command, input: { client_id: "original", target_user_id: target, feature_key: "admin", allowed: false } }; await executeAdminCommand(f.port, f.auth, () => "e".repeat(64), value); expect(f.log).toEqual(["master", "reserve"]); expect(f.auth.ban).not.toHaveBeenCalled(); });
 it("replays only after current master guard, even when the operation is complete", async () => { const f = fixture(); f.setPhase("complete"); vi.mocked(f.port.requireMaster).mockRejectedValue(new Error("role revoked")); await expect(executeAdminCommand(f.port, f.auth, () => "unused", request)).rejects.toThrow("revoked"); expect(f.port.reserve).not.toHaveBeenCalled(); });
 it("a failed reconciliation write never compensates by enabling access", async () => { const f = fixture(); vi.mocked(f.auth.create).mockRejectedValue(new Error("Auth")); vi.mocked(f.port.transition).mockRejectedValue(new Error("lost master")); await expect(executeAdminCommand(f.port, f.auth, () => "x", request)).rejects.toThrow("Auth"); expect(f.fence).toBe(true); expect(f.auth.ban).not.toHaveBeenCalled(); });
 it("unknown in-flight Auth mutation keeps the execution claim and moderation fence", async () => { const f = fixture(); vi.mocked(f.auth.create).mockRejectedValue(new AdminAuthUncertainError()); await expect(executeAdminCommand(f.port, f.auth, () => "a".repeat(64), request)).rejects.toBeInstanceOf(AdminAuthUncertainError); expect(f.port.transition).toHaveBeenLastCalledWith(opId, "needs_reconciliation", false); expect(f.port.complete).not.toHaveBeenCalled(); expect(f.fence).toBe(true); });
 it("a proven terminated failure permits another claim, while keeping data blocked", async () => { const f = fixture(); vi.mocked(f.auth.create).mockRejectedValue(new Error("known terminal validation error")); await expect(executeAdminCommand(f.port, f.auth, () => "a".repeat(64), request)).rejects.toThrow(); expect(f.port.transition).toHaveBeenLastCalledWith(opId, "needs_reconciliation", true); expect(f.fence).toBe(true); });
 it("reconciliation cannot bypass an existing in-flight execution claim", async () => { const f = fixture(); vi.mocked(f.port.claim).mockRejectedValue(new Error("execution still held")); await expect(executeAdminCommand(f.port, f.auth, () => "unused", { command: "admin.operation.reconcile", input: { client_id: "resume", operation_id: opId } })).rejects.toThrow("still held"); expect(f.auth.verifyCreated).not.toHaveBeenCalled(); expect(f.auth.ban).not.toHaveBeenCalled(); expect(f.port.transition).not.toHaveBeenCalled(); });
 it("two simultaneous retries cannot issue two Auth mutations", async () => { const f = fixture(); let claimed = false; const reserve = f.port.reserve; f.port.reserve = vi.fn(async intent => { if (claimed) throw new Error("execution held"); claimed = true; return reserve(intent); }); let finish!: () => void; const gate = new Promise<void>(resolve => { finish = resolve; }); vi.mocked(f.auth.create).mockImplementation(async () => gate); const first = executeAdminCommand(f.port, f.auth, () => "a".repeat(64), request); await vi.waitFor(() => expect(f.auth.create).toHaveBeenCalledTimes(1)); await expect(executeAdminCommand(f.port, f.auth, () => "a".repeat(64), request)).rejects.toThrow("execution held"); expect(f.auth.create).toHaveBeenCalledTimes(1); finish(); expect((await first).phase).toBe("complete"); });
 it("a late unban after an uncertain response cannot release application data", async () => { const f = fixture("admin.user.force_password"); let authBanned = true, claimed = true; let lateUnban!: () => void; vi.mocked(f.auth.ban).mockImplementation(async (_, blocked) => { if (blocked) { authBanned = true; return; } lateUnban = () => { authBanned = false; }; throw new AdminAuthUncertainError(); }); const transition = f.port.transition; f.port.transition = vi.fn(async (operationId, phase, release) => { if (phase === "needs_reconciliation" && release) claimed = false; return transition(operationId, phase, release); }); await expect(executeAdminCommand(f.port, f.auth, () => "a".repeat(64), { command: "admin.user.force_password", input: { client_id: "original", target_user_id: target } })).rejects.toBeInstanceOf(AdminAuthUncertainError); lateUnban(); expect(authBanned).toBe(false); expect(f.fence).toBe(true); expect(claimed).toBe(true); expect(f.port.complete).not.toHaveBeenCalled(); });
});
describe("Admin strict input boundary", () => {
 it.each(["user_id", "actor_user_id", "target_user_id", "role", "app_metadata", "user_metadata"])("rejects injected %s on creation", key => { expect(() => decodeAdminCommand({ ...request, input: { ...request.input, [key]: target } })).toThrow(); });
 it.each([null, [], { command: "admin.user.delete", input: { client_id: "bad", target_user_id: target } }, { ...request, actor_user_id: actor }, { ...request, input: { ...request.input, temporary_password: "tiny" } }, { ...request, input: { ...request.input, temporary_password: "🙂".repeat(19) } }, { ...request, input: { ...request.input, email: "invalid" } }])("rejects invalid privileged request %#", value => { expect(() => decodeAdminCommand(value)).toThrow(); });
 it("accepts exactly 72 UTF-8 bytes and clones credentials only in transient command memory", () => { const value = { ...request, input: { ...request.input, temporary_password: "a".repeat(72) } }; expect(decodeAdminCommand(value)).toEqual(value); expect(decodeAdminCommand(value)).not.toBe(value); });
 it("rejects malformed target UUIDs and unknown entitlements", () => { expect(() => decodeAdminCommand({ command: "admin.user.block", input: { client_id: "b", target_user_id: "someone" } })).toThrow(); expect(() => decodeAdminCommand({ command: "admin.user.entitlement", input: { client_id: "e", target_user_id: target, feature_key: "superuser", allowed: true } })).toThrow(); });
});
describe("Usable master predicate shared with locked SQL", () => {
 const active: AdminMasterEligibility = { role: "master", status: "active", must_change_password: false, admin_allowed: true, auth_banned: false, deleted: false, anonymous: false };
 it("protects the only usable master", () => { expect(() => preserveUsableMaster(active, [])).toThrow("último master"); expect(() => preserveUsableMaster(active, [active])).not.toThrow(); });
 it.each([{ status: "blocked" as const }, { must_change_password: true }, { admin_allowed: false }, { auth_banned: true }, { deleted: true }, { anonymous: true }, { role: "user" as const }])("does not count unavailable master state %#", patch => { const unavailable = { ...active, ...patch }; expect(usableMaster(unavailable)).toBe(false); expect(() => preserveUsableMaster(active, [unavailable])).toThrow(); });
 it("a previously unavailable master can be changed without reducing the usable set", () => { expect(() => preserveUsableMaster({ ...active, status: "blocked" }, [])).not.toThrow(); });
});
