import { beforeEach, describe, expect, it, vi } from "vitest";
import { CALENDAR_SCOPES, CalendarProviderError, decodeCalendarCommand, defaultWindow, dueMeetingReminders, executeCalendarCommand, finishCalendarConnection, googleEvent, safeGoogleEventLink, sufficientCalendarScopes, synchronizeCalendars, validWindow, type CalendarCipher, type CalendarEvent, type CalendarProvider, type CalendarRepository, type CalendarSnapshot, type PrivateGoogleAccount } from "../../src/core/calendario";
import { eventsOnDay, timedSegments } from "../../src/components/features/calendario/calendar-projections";
const owner = "25000000-0000-4000-8000-000000000001", accountId = "25000000-0000-4000-8000-000000000002", sourceId = "25000000-0000-4000-8000-000000000003", runId = "25000000-0000-4000-8000-000000000004";
const envelope = { version: 1 as const, key_id: "test", iv: "fake", ciphertext: "fake", tag: "fake" }, window = { start_day: "2026-10-01", end_day: "2026-11-01" }, now = "2026-10-09T12:00:00Z";
let repo: CalendarRepository, provider: CalendarProvider, cipher: CalendarCipher, snapshot: CalendarSnapshot, account: PrivateGoogleAccount;
beforeEach(() => {
 snapshot = { items: [], accounts: [{ id: accountId, user_id: owner, email: "calendar@example.invalid", scopes: [...CALENDAR_SCOPES], status: "connected", last_synced_at: null }], calendars: [{ id: sourceId, user_id: owner, account_id: accountId, name: "Work", color_key: "calendar", selected: true }], sync_runs: [], window, preferences: { default_calendar_view: "month", meeting_reminders_enabled: true, meeting_reminder_minutes: 10 } };
 account = { id: accountId, user_id: owner, google_sub: "sub-one", revision: "0", credential_version: 1, status: "connected", tokens: envelope, calendars: [{ id: sourceId, google_id: "opaque-id@group.calendar.google.com", selected: true, sync_token: "old", window }] };
 repo = { userId: owner, requireAccess: vi.fn(), snapshot: vi.fn(async () => snapshot), beginFlow: vi.fn(async () => ({ account_id: accountId })), consumeFlow: vi.fn(async () => ({ account_id: accountId, reconnect: false })), failFlow: vi.fn(), privateAccount: vi.fn(async () => account), connect: vi.fn(), saveTokens: vi.fn(async () => account), resetCursor: vi.fn(async () => ({ ...account, revision: "1" })), commitEvents: vi.fn(async input => ({ ...input.account, revision: String(Number(input.account.revision) + 1) })), select: vi.fn(), disconnect: vi.fn(async () => ({ ...account, status: "revocation_pending" as const, revision: "1" })), finishDisconnect: vi.fn(), link: vi.fn(), run: vi.fn(async () => ({ id: runId, user_id: owner, account_id: null, channel: "web" as const, status: "running" as const, calendar_count: 0, event_count: 0, started_at: now, finished_at: null })), finishRun: vi.fn(), reauthorize: vi.fn() };
 provider = { exchange: vi.fn(async () => ({ access_token: "access", refresh_token: "refresh", expires_at: "2026-10-09T14:00:00Z", scopes: [...CALENDAR_SCOPES] })), profile: vi.fn(async () => ({ sub: "sub-one", email: "calendar@example.invalid" })), calendars: vi.fn(async () => [{ google_id: "source", name: "Work", color_key: "calendar", deleted: false }]), refresh: vi.fn(async () => ({ access_token: "new", refresh_token: null, expires_at: "2026-10-09T14:00:00Z", scopes: null })), events: vi.fn(async () => ({ items: [], next_page_token: null, next_sync_token: "new" })), revoke: vi.fn() };
 cipher = { encrypt: vi.fn(() => envelope), decrypt: vi.fn(() => ({ access_token: "access", refresh_token: "refresh", expires_at: "2026-10-09T14:00:00Z", scopes: [...CALENDAR_SCOPES] })) };
});
describe("Calendar civil semantics and strict commands", () => {
 it.each(["UTC", "America/Sao_Paulo"])("three-day all-day interval remains identical in %s", timezone => { const previous = process.env.TZ; process.env.TZ = timezone; try { const remote = googleEvent({ id: "multi", start: { date: "2026-10-09" }, end: { date: "2026-10-12" } }); const event = { ...remote, id: "multi", user_id: owner, account_id: accountId, calendar_id: sourceId, linked_capture_id: null, habit_id: null } as CalendarEvent; for (const day of ["2026-10-09", "2026-10-10", "2026-10-11"]) expect(eventsOnDay([event], day)).toHaveLength(1); expect(eventsOnDay([event], "2026-10-12")).toEqual([]); expect(timedSegments([event], "2026-10-10")).toEqual([]); } finally { if (previous === undefined) delete process.env.TZ; else process.env.TZ = previous; } });
 it("uses civil app today for initial window even near UTC midnight", () => { expect(defaultWindow("2026-10-09T01:00:00Z")).toEqual(defaultWindow("2026-10-08")); expect(validWindow({ start_day: "2026-02-30", end_day: "2026-03-02" })).toBe(false); expect(validWindow({ start_day: "2026-01-01", end_day: "2030-01-01" })).toBe(false); });
 it.each(["https://evil.invalid/calendar/event?x", "javascript:alert(1)", "https://www.google.com@evil.invalid/calendar/event", "https://www.google.com/calendar/eventual"])("rejects unsafe event link %s", link => expect(safeGoogleEventLink(link)).toBeNull());
 it("accepts actual email scope alias and requires both Calendar read grants", () => { expect(sufficientCalendarScopes([...CALENDAR_SCOPES].map(scope => scope === "email" ? "https://www.googleapis.com/auth/userinfo.email" : scope))).toBe(true); expect(sufficientCalendarScopes([...CALENDAR_SCOPES].slice(0, -1))).toBe(false); });
 it.each([{ command: "calendar.select", input: { client_id: "x", calendar_id: sourceId, selected: true, user_id: owner } }, { command: "calendar.sync", input: { client_id: "x", ...window, arbitrary: true } }, { command: "calendar.disconnect", input: { client_id: "x", account_id: "bad" } }, { command: "calendar.event.link", input: { client_id: "x", event_id: sourceId, capture_id: null }, owner }])("rejects actor spoofing, wrong fields and invalid targets %#", request => expect(() => decodeCalendarCommand(request)).toThrow());
 it("inherits popup reminders and excludes all-day/disabled/past meetings", () => { expect(googleEvent({ id: "x", start: { dateTime: now }, end: { dateTime: "2026-10-09T13:00:00Z" } }, [{ method: "popup", minutes: 10 }]).reminder_minutes).toBe(10); const e = { id: "x", starts_at: "2026-10-09T12:05:00Z", all_day: false } as CalendarEvent; expect(dueMeetingReminders([e], snapshot.preferences, now)).toEqual([e]); expect(dueMeetingReminders([{ ...e, all_day: true }], snapshot.preferences, now)).toEqual([]); expect(dueMeetingReminders([e], { ...snapshot.preferences, meeting_reminders_enabled: false }, now)).toEqual([]); });
});
describe("OAuth exchange is behind atomic replay guard", () => {
 const input = { flow_id: runId, digest: "a".repeat(64), code: "ephemeral-code", verifier: "ephemeral-verifier" };
 it("consumes before any SDK transport and stores actual grants encrypted only", async () => { await finishCalendarConnection(repo, provider, cipher, input); expect(vi.mocked(repo.consumeFlow).mock.invocationCallOrder[0]).toBeLessThan(vi.mocked(provider.exchange).mock.invocationCallOrder[0]!); expect(repo.connect).toHaveBeenCalledWith(expect.objectContaining({ scopes: [...CALENDAR_SCOPES], tokens: envelope })); expect(JSON.stringify(vi.mocked(repo.connect).mock.calls)).not.toContain("ephemeral"); });
 it("replay/owner/session failure cannot exchange", async () => { vi.mocked(repo.consumeFlow).mockRejectedValue(new Error("consumed")); await expect(finishCalendarConnection(repo, provider, cipher, input)).rejects.toThrow(); expect(provider.exchange).not.toHaveBeenCalled(); });
 it("denied grants fail before profile or persistence", async () => { vi.mocked(provider.exchange).mockResolvedValue({ access_token: "access", refresh_token: "refresh", expires_at: now, scopes: ["openid", "email"] }); await expect(finishCalendarConnection(repo, provider, cipher, input)).rejects.toThrow(); expect(provider.profile).not.toHaveBeenCalled(); expect(repo.connect).not.toHaveBeenCalled(); expect(repo.failFlow).toHaveBeenCalled(); });
 it("reconnect rejects a different Google subject", async () => { vi.mocked(repo.consumeFlow).mockResolvedValue({ account_id: accountId, reconnect: true }); vi.mocked(provider.profile).mockResolvedValue({ sub: "different", email: "new@example.invalid" }); await expect(finishCalendarConnection(repo, provider, cipher, input)).rejects.toThrow(); expect(repo.connect).not.toHaveBeenCalled(); });
});
describe("Incremental sync and disconnect", () => {
 it("guard rejects before reading tokens or Google", async () => { vi.mocked(repo.requireAccess).mockRejectedValue(new Error("denied")); await expect(synchronizeCalendars(repo, provider, cipher, window, now, "x")).rejects.toThrow(); expect(repo.snapshot).not.toHaveBeenCalled(); expect(provider.events).not.toHaveBeenCalled(); });
 it("incremental retains cursor, full navigation expansion removes cursor", async () => { await synchronizeCalendars(repo, provider, cipher, window, now, "x"); expect(provider.events).toHaveBeenCalledWith("access", account.calendars[0]!.google_id, expect.objectContaining({ sync_token: "old" })); vi.mocked(provider.events).mockClear(); await synchronizeCalendars(repo, provider, cipher, { start_day: "2026-09-01", end_day: "2026-12-01" }, now, "expanded"); expect(provider.events).toHaveBeenCalledWith("access", account.calendars[0]!.google_id, expect.objectContaining({ sync_token: null })); });
 it("410 deletes local cursor/cache first then starts a new complete series", async () => { vi.mocked(provider.events).mockRejectedValueOnce(new CalendarProviderError("expired_cursor")).mockResolvedValueOnce({ items: [], next_page_token: "next", next_sync_token: null }).mockResolvedValueOnce({ items: [], next_page_token: null, next_sync_token: "fresh" }); await synchronizeCalendars(repo, provider, cipher, window, now, "410"); expect(repo.resetCursor).toHaveBeenCalledOnce(); expect(repo.commitEvents).toHaveBeenCalledWith(expect.objectContaining({ account: expect.objectContaining({ revision: "1" }), reset: true, sync_token: "fresh" })); expect(repo.finishRun).toHaveBeenCalledWith(runId, "complete", 1, 0); });
 it("never commits partial pages or a repeated page token", async () => { vi.mocked(provider.events).mockResolvedValue({ items: [], next_page_token: "repeat", next_sync_token: null }); await expect(synchronizeCalendars(repo, provider, cipher, window, now, "repeat")).rejects.toThrow(); expect(repo.commitEvents).not.toHaveBeenCalled(); expect(repo.finishRun).toHaveBeenCalledWith(runId, "failed", 0, 0); });
 it("requires final cursor and refuses more than 8 pages", async () => { vi.mocked(provider.events).mockResolvedValue({ items: [], next_page_token: null, next_sync_token: null }); await expect(synchronizeCalendars(repo, provider, cipher, window, now, "no-cursor")).rejects.toThrow(); expect(repo.commitEvents).not.toHaveBeenCalled(); });
 it("only selected sources participate in Google requests", async () => { account.calendars[0]!.selected = false; await synchronizeCalendars(repo, provider, cipher, window, now, "hidden"); expect(provider.events).not.toHaveBeenCalled(); expect(repo.finishRun).toHaveBeenCalledWith(runId, "complete", 0, 0); });
 it("refresh keeps omitted refresh token and scopes, using bumped credential version", async () => { vi.mocked(cipher.decrypt).mockReturnValue({ access_token: "expired", refresh_token: "keep", expires_at: now, scopes: [...CALENDAR_SCOPES] }); await synchronizeCalendars(repo, provider, cipher, window, now, "refresh"); expect(provider.refresh).toHaveBeenCalledWith("keep"); expect(cipher.encrypt).toHaveBeenCalledWith(owner, accountId, 2, expect.objectContaining({ refresh_token: "keep", scopes: [...CALENDAR_SCOPES] })); });
 it("invalid grant marks reauthorization and records failure", async () => { vi.mocked(provider.events).mockRejectedValue(new CalendarProviderError("reauthorize")); await expect(synchronizeCalendars(repo, provider, cipher, window, now, "reauth")).rejects.toThrow(); expect(repo.reauthorize).toHaveBeenCalledWith(account); expect(repo.finishRun).toHaveBeenCalledWith(runId, "failed", 0, 0); });
 it("disconnect fences before revoke; uncertain revoke never finishes deletion", async () => { vi.mocked(provider.revoke).mockRejectedValue(new CalendarProviderError("unavailable")); await expect(executeCalendarCommand(repo, provider, cipher, { command: "calendar.disconnect", input: { client_id: "x", account_id: accountId } }, now)).rejects.toThrow(); expect(vi.mocked(repo.disconnect).mock.invocationCallOrder[0]).toBeLessThan(vi.mocked(provider.revoke).mock.invocationCallOrder[0]!); expect(repo.finishDisconnect).not.toHaveBeenCalled(); });
 it("completed receipt returns snapshot without revoke, unknown account refuses", async () => { vi.mocked(repo.disconnect).mockResolvedValue(null); await executeCalendarCommand(repo, provider, cipher, { command: "calendar.disconnect", input: { client_id: "completed", account_id: accountId } }, now); expect(provider.revoke).not.toHaveBeenCalled(); });
});
