import { describe, expect, it } from "vitest";
import { createMemoryVaultPort } from "../../src/adapters/crypto/memory-vault";
import { prepareVaultMutation } from "../../src/core/cofre/use-cases";
import { encodeBase64, decodeVaultInput } from "../../src/core/cofre/validation";
import type { VaultInput, VaultMasterWrap } from "../../src/core/cofre/types";
const user = "11111111-1111-4111-8111-111111111111", id = "22222222-2222-4222-8222-222222222222", now = "2026-10-09T12:00:00Z", envelope = { iv: encodeBase64(new Uint8Array(12)), ciphertext: encodeBase64(new Uint8Array(48)) };
const master: VaultMasterWrap = { kdf: { algorithm: "argon2id", memory_kib: 65536, iterations: 3, parallelism: 1, salt: encodeBase64(new Uint8Array(16)) }, envelope };
const create: VaultInput = { command: "vault.create", input: { client_id: "create", expected_revision: "0", master, recovery: envelope, consent: true } };
describe("T024 cipher-only commands", () => {
 it("replays once, rejects divergent payload and preserves the recovery wrapper on rewrap", async () => { const port = createMemoryVaultPort(user, () => now); const [a,b] = await Promise.all([port.execute(create),port.execute(create)]); expect(a).toEqual(b); await expect(port.execute({ ...create, input: { ...create.input, expected_revision: "99" } })).rejects.toMatchObject({ code: "CONFLICT" }); const before = await port.snapshot(); await port.execute({ command: "vault.master.rewrap", input: { client_id: "rewrap", expected_revision: before.revision, master: { ...master, envelope: { ...envelope, iv: encodeBase64(new Uint8Array(12).fill(1)) } } } }); expect((await port.snapshot()).header?.recovery).toEqual(before.header?.recovery); });
 it("CRUD cipher versions, soft deletion and restoration are atomic and immutable outside the port", async () => { const port = createMemoryVaultPort(user, () => now); await port.execute(create); const insert: VaultInput = { command: "vault.item.create", input: { client_id: "item", expected_revision: "1", id, version: 1, envelope } }; await port.execute(insert); const state = await port.snapshot(); state.items[0]!.envelope.ciphertext = "outside"; expect((await port.snapshot()).items[0]!.envelope.ciphertext).toBe(envelope.ciphertext); await expect(port.execute({ command: "vault.item.update", input: { client_id: "bad-version", expected_revision: "2", id, version: 1, envelope } })).rejects.toThrow("versão"); expect((await port.snapshot()).revision).toBe("2"); await port.execute({ command: "vault.item.delete", input: { client_id: "delete", expected_revision: "2", id } }); await port.execute({ command: "vault.item.restore", input: { client_id: "restore", expected_revision: "3", id } }); expect((await port.snapshot()).items[0]).toMatchObject({ version: 1, envelope, deleted_at: null }); });
 it("exact metadata contains no envelope, title, kit or free fields", async () => { const port = createMemoryVaultPort(user, () => now); const result = prepareVaultMutation(await port.snapshot(), user, create, now); expect(Object.keys(result.metadata).sort()).toEqual(["id","occurred_at","operation","user_id","version"]); expect(JSON.stringify(result.metadata)).not.toContain("ciphertext"); expect(() => decodeVaultInput({ ...create, input: { ...create.input, password: "plaintext" } })).toThrow(); expect(() => decodeVaultInput({ command: "vault.audit", input: { client_id: "audit", expected_revision: "0", operation: "copied", item_id: id, details: "secret" } })).toThrow(); });
});
