import { describe, expect, it, vi } from "vitest";
import { argon2id } from "hash-wasm";
import { prepareVault, unlockVault, recoverVault, changeMasterPassword, importSessionKey, VaultSession, type VaultKdfPort } from "../../src/core/cofre/crypto";
import { decodeVaultInput, assertVaultSnapshot } from "../../src/core/cofre/validation";
import type { VaultCipherItem, VaultHeader, VaultPlainItem } from "../../src/core/cofre/types";
const user = "11111111-1111-4111-8111-111111111111", stamp = "2026-10-09T12:00:00Z";
const derive: VaultKdfPort = async (password, salt, kdf) => new Uint8Array(await argon2id({ password, salt, memorySize: kdf.memory_kib, iterations: kdf.iterations, parallelism: kdf.parallelism, hashLength: 32, outputType: "binary" }));
const plain: VaultPlainItem = { title: "Segredo real de teste", kind: "login", username: "account@example.test", password: "never-server-plaintext", url: "https://example.test", note: "Nota privada de teste" };
const header = (p: Awaited<ReturnType<typeof prepareVault>>): VaultHeader => ({ user_id: user, schema_version: 1, master: p.master, recovery: p.recovery, consent_at: stamp, created_at: stamp, updated_at: stamp });
const row = async (session: VaultSession, id = "22222222-2222-4222-8222-222222222222"): Promise<VaultCipherItem> => ({ id, user_id: user, version: 1, envelope: await session.encrypt(id, 1, plain), deleted_at: null, created_at: stamp, updated_at: stamp });
describe("T024 real Argon2id and WebCrypto", () => {
 it("session AES-256 key cannot be exported", async () => { const key = await importSessionKey(crypto.getRandomValues(new Uint8Array(32))); expect(key.extractable).toBe(false); await expect(crypto.subtle.exportKey("raw", key)).rejects.toThrow(); });
 it("creation proves both kit halves byte by byte; fresh password unlock decrypts", async () => { const p = await prepareVault(user, "UmaSenhaMestraForte2026!", derive); await expect(p.prove(p.kit.a, p.kit.b)).resolves.toBe(true); const item = await row(p.session), fresh = await unlockVault(header(p), "UmaSenhaMestraForte2026!", derive); expect(await fresh.decrypt(item)).toEqual(plain); expect(JSON.stringify(header(p))).not.toContain(plain.password); p.dispose(); fresh.lock(); });
 it("AAD rejects swapped item payload, owner and version", async () => { const key = await importSessionKey(crypto.getRandomValues(new Uint8Array(32))), session = new VaultSession(user, key), item = await row(session); await expect(session.decrypt({ ...item, id: "33333333-3333-4333-8333-333333333333" })).rejects.toThrow(); await expect(session.decrypt({ ...item, version: 2 })).rejects.toThrow(); await expect(new VaultSession("other", key).decrypt({ ...item, user_id: "other" })).rejects.toThrow(); });
 it("the old recovery kit stays valid after password rewrap, from a clean session", async () => { const p = await prepareVault(user, "UmaSenhaMestraForte2026!", derive); await p.prove(p.kit.a, p.kit.b); const initial = header(p), item = await row(p.session); const changed = { ...initial, master: await changeMasterPassword(initial, "UmaSenhaMestraForte2026!", "UmaFraseNovaDeSenha2027!", derive) }; p.dispose(); await expect(unlockVault(changed, "UmaSenhaMestraForte2026!", derive)).rejects.toThrow(); const recovery = await recoverVault(changed, p.kit.a, p.kit.b, "UmaRecuperacaoSegura2028!", derive); expect(await recovery.session.decrypt(item)).toEqual(plain); const after = { ...changed, master: recovery.master }; expect(after.recovery).toEqual(initial.recovery); expect(await (await unlockVault(after, "UmaRecuperacaoSegura2028!", derive)).decrypt(item)).toEqual(plain); });
 it("incomplete, corrupted and foreign kit halves fail closed", async () => { const p = await prepareVault(user, "UmaSenhaMestraForte2026!", derive); await expect(p.prove(p.kit.a, p.kit.a)).rejects.toThrow(); const broken = JSON.parse(p.kit.b); broken.data = broken.data.replace(/^./, broken.data[0] === "A" ? "B" : "A"); await expect(p.prove(p.kit.a, JSON.stringify(broken))).rejects.toThrow(); const foreign = JSON.parse(p.kit.a); foreign.user_id = "other"; await expect(p.prove(JSON.stringify(foreign), p.kit.b)).rejects.toThrow(); p.dispose(); });
 it("locking rejects encryption and decryption and invalid/plain input never crosses command parsing", async () => { const session = new VaultSession(user, await importSessionKey(crypto.getRandomValues(new Uint8Array(32)))), item = await row(session); session.lock(); await expect(session.decrypt(item)).rejects.toThrow("Desbloqueie"); await expect(session.encrypt(item.id, 2, plain)).rejects.toThrow("Desbloqueie"); expect(() => decodeVaultInput({ command: "vault.item.create", input: { client_id: "x", expected_revision: "0", id: item.id, version: 1, envelope: item.envelope, title: plain.title } })).toThrow(); });
 it("a corrupt item remains in a readable snapshot for per-item diagnosis", async () => { const p = await prepareVault(user, "UmaSenhaMestraForte2026!", derive), item = await row(p.session); item.envelope.ciphertext = "corrupted"; const snapshot = { revision: "1", header: header(p), items: [item] }; expect(() => assertVaultSnapshot(snapshot, user)).not.toThrow(); await expect(p.session.decrypt(item)).rejects.toThrow(); p.dispose(); });
 it.each(["invalid-json", "bad-checksum", "short-half"])("clears both owned half buffers when recovery fails with %s", async failure => {
  const p = await prepareVault(user, "UmaSenhaMestraForte2026!", derive), part = JSON.parse(p.kit.b) as { data: string; checksum: string };
  const broken = failure === "invalid-json" ? "invalid-json" : JSON.stringify({ ...part, ...(failure === "bad-checksum" ? { checksum: "invalid-checksum" } : { data: btoa("short") }) });
  const allocations = vi.spyOn(Uint8Array, "from");
  try {
   await expect(recoverVault(header(p), p.kit.a, broken, "UmaSenhaNovaForte2027!", derive)).rejects.toThrow();
   const buffers = allocations.mock.results.filter(result => result.type === "return").map(result => result.value as Uint8Array);
   expect(buffers.length).toBeGreaterThan(0); expect(buffers.every(bytes => bytes.every(byte => byte === 0))).toBe(true);
  } finally { allocations.mockRestore(); p.dispose(); }
 });
});
