import { unlockVault, recoverVault, type VaultSession } from "../../../src/core/cofre/crypto";
import { assertVaultSnapshot } from "../../../src/core/cofre/validation";
import type { VaultSnapshot } from "../../../src/core/cofre/types";
import { deriveVaultKey, cancelVaultDerivations } from "../../../src/adapters/crypto/argon2";

interface Packet { version:1;source_project_ref:string;target_project_ref:string;archive_sha256:string;fixture_user_id:string;vault:VaultSnapshot;files_verified:number;created_at:string }
const object=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==="object"&&!Array.isArray(v);
function packetFrom(value:unknown):Packet {
 const fields=["version","source_project_ref","target_project_ref","archive_sha256","fixture_user_id","vault","files_verified","created_at"];
 if(!object(value)||Object.keys(value).length!==fields.length||!fields.every(field=>Object.hasOwn(value,field))||value.version!==1||value.source_project_ref!=="rishenjoikgmfubmnfiu"||typeof value.target_project_ref!=="string"||!/^[a-z]{20}$/.test(value.target_project_ref)||value.target_project_ref===value.source_project_ref||typeof value.archive_sha256!=="string"||!/^[a-f0-9]{64}$/.test(value.archive_sha256)||typeof value.fixture_user_id!=="string"||!/^[a-f0-9-]{36}$/i.test(value.fixture_user_id)||!Number.isSafeInteger(value.files_verified)||Number(value.files_verified)<1||Number(value.files_verified)>10||typeof value.created_at!=="string"||!Number.isFinite(Date.parse(value.created_at)))throw new Error("INVALID_PACKET");
 assertVaultSnapshot(value.vault,value.fixture_user_id);if(value.vault.header===null||value.vault.items.length<1||value.vault.items.length>10)throw new Error("INVALID_PACKET");return value as unknown as Packet;
}
async function countReadable(session:VaultSession,snapshot:VaultSnapshot) {let count=0;try{for(const item of snapshot.items){await session.decrypt(item);count++;}return count;}finally{session.lock();}}
function input(id:string) {const element=document.getElementById(id);if(!(element instanceof HTMLInputElement))throw new Error("INSPECTOR_UNAVAILABLE");return element;}
const packetInput=input("packet"),password=input("password"),left=input("kit-a"),right=input("kit-b"),passwordForm=document.getElementById("password-form"),kitForm=document.getElementById("kit-form"),status=document.getElementById("status"),passwordResult=document.getElementById("password-result"),kitResult=document.getElementById("kit-result"),clear=document.getElementById("clear");
if(!passwordForm||!kitForm||!status||!passwordResult||!kitResult||!clear)throw new Error("INSPECTOR_UNAVAILABLE");
let packet:Packet|null=null,activeSession:VaultSession|null=null,generation=0,busy=false;
const buttons=[...document.querySelectorAll<HTMLButtonElement>("button[type=submit]")];
function controls(){for(const button of buttons)button.disabled=busy||packet===null;}
function forget(){generation++;activeSession?.lock();activeSession=null;cancelVaultDerivations();packet=null;busy=false;packetInput.value="";password.value="";left.value="";right.value="";passwordResult!.textContent="Senha original: ainda não verificada.";kitResult!.textContent="Kit original: ainda não verificado.";status!.textContent="Dados descartados. Escolha um pacote privado para recomeçar.";controls();}
packetInput.addEventListener("change",async()=>{generation++;const current=generation;activeSession?.lock();activeSession=null;cancelVaultDerivations();packet=null;busy=false;password.value="";left.value="";right.value="";passwordResult!.textContent="Senha original: ainda não verificada.";kitResult!.textContent="Kit original: ainda não verificado.";controls();try{const file=packetInput.files?.[0];if(!file||file.size>1048576)throw new Error();const loaded=packetFrom(JSON.parse(await file.text()));if(current!==generation)return;packet=loaded;status!.textContent="Pacote carregado: "+loaded.vault.items.length+" item(ns) cifrado(s). O registro do CLI informa "+loaded.files_verified+" arquivo(s) conferido(s).";}catch{if(current===generation)status!.textContent="Pacote inválido ou grande demais. Selecione o pacote gerado pelo CLI supervisionado.";}finally{controls();}});
passwordForm.addEventListener("submit",async event=>{event.preventDefault();if(!packet||busy)return;const value=packet,current=generation,secret=password.value;password.value="";busy=true;controls();status!.textContent="Derivando a chave com Argon2id e conferindo os itens…";let session:VaultSession|null=null;try{session=await unlockVault(value.vault.header!,secret,deriveVaultKey);if(current!==generation){session.lock();return;}activeSession=session;const count=await countReadable(session,value.vault);if(current===generation){passwordResult!.textContent="Senha original: "+count+" item(ns) decifrado(s).";status!.textContent="Decifragem confirmada. Nenhum conteúdo foi exibido ou enviado.";}}catch{if(current===generation){passwordResult!.textContent="Senha original: verificação falhou.";status!.textContent="Não foi possível decifrar todos os itens. Confira o pacote e a senha original; não considere este ensaio aprovado.";}}finally{session?.lock();if(activeSession===session)activeSession=null;if(current===generation){busy=false;controls();}}});
kitForm.addEventListener("submit",async event=>{event.preventDefault();if(!packet||busy)return;const value=packet,current=generation,a=left.files?.[0],b=right.files?.[0];left.value="";right.value="";busy=true;controls();status!.textContent="Conferindo as duas metades do kit original…";let session:VaultSession|null=null;try{if(!a||!b||a.size>1024||b.size>1024)throw new Error();const parts=await Promise.all([a.text(),b.text()]);if(current!==generation)return;const temporaryPassword="RestoreVerification-"+Array.from(crypto.getRandomValues(new Uint8Array(32)),byte=>byte.toString(16).padStart(2,"0")).join("");const recovered=await recoverVault(value.vault.header!,parts[0]!,parts[1]!,temporaryPassword,deriveVaultKey);session=recovered.session;if(current!==generation){session.lock();return;}activeSession=session;const count=await countReadable(session,value.vault);if(current===generation){kitResult!.textContent="Kit original: "+count+" item(ns) decifrado(s).";status!.textContent="Kit confirmado em sessão criptográfica nova. O wrapper temporário foi calculado apenas em memória; o banco não mudou.";}}catch{if(current===generation){kitResult!.textContent="Kit original: verificação falhou.";status!.textContent="Não foi possível recuperar todos os itens. Confira as duas metades originais e o pacote; não considere este ensaio aprovado.";}}finally{session?.lock();if(activeSession===session)activeSession=null;if(current===generation){busy=false;controls();}}});
clear.addEventListener("click",forget);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="hidden")forget();});window.addEventListener("blur",()=>{if(busy)forget();});window.addEventListener("pagehide",forget);controls();
