"use client";
import { useId, useRef, useState, type FormEvent, type RefObject } from "react";
import type { VaultCipherItem, VaultPlainItem, VaultInput, VaultPort } from "@/core/cofre/types";
import type { VaultSession } from "@/core/cofre/crypto";
import { Drawer } from "@/components/ui/dialog";
import { Field } from "@/components/ui/field";
import { Button } from "@/components/ui/button";
const blank: VaultPlainItem = { title: "", kind: "login", username: "", password: "", url: "", note: "" };
export function VaultEditor({ item, plain, session, revision, port, returnFocusRef, onClose, onSaved, onAccessLost }: { item?: VaultCipherItem; plain?: VaultPlainItem; session: VaultSession; revision: string; port: VaultPort; returnFocusRef: RefObject<HTMLElement | null>; onClose(): void; onSaved(): Promise<void>; onAccessLost(): void }) {
 const [value, setValue] = useState(plain ?? blank), [pending, setPending] = useState(false), [error, setError] = useState(""); const first = useRef<HTMLInputElement>(null), form = useId(), busy = useRef(false), retained = useRef<{ fingerprint: string; request: VaultInput } | null>(null);
 const update = (key: keyof VaultPlainItem, v: string) => { setValue(current => ({ ...current, [key]: v })); setError(""); };
 async function submit(event: FormEvent) { event.preventDefault(); if (busy.current) return; busy.current = true; setPending(true); setError(""); try { const fingerprint = JSON.stringify(value); if (retained.current?.fingerprint !== fingerprint) { const id = item?.id ?? crypto.randomUUID(), version = (item?.version ?? 0) + 1; retained.current = { fingerprint, request: { command: item ? "vault.item.update" : "vault.item.create", input: { id, version, envelope: await session.encrypt(id, version, value), expected_revision: revision, client_id: crypto.randomUUID() } } }; } await port.execute(retained.current.request); setValue(blank); await onSaved(); onClose(); } catch (failure) { if (failure && typeof failure === "object" && "code" in failure && ["UNAUTHENTICATED", "FORBIDDEN", "SESSION_CHANGED"].includes(String(failure.code))) { setValue(blank); retained.current = null; onAccessLost(); } else setError(failure instanceof Error ? failure.message : "Não foi possível salvar. Tente novamente."); } finally { busy.current = false; setPending(false); } }
 return <Drawer open title={item ? "Editar item do Cofre" : "Novo item do Cofre"} initialFocusRef={first} returnFocusRef={returnFocusRef} dismissible={!pending} closeOnBackdrop={false} onClose={onClose} footer={<><Button disabled={pending} onClick={onClose}>Cancelar</Button><Button variant="primary" type="submit" form={form} loading={pending}>Salvar item cifrado</Button></>}><form id={form} onSubmit={submit} className="vault-form" noValidate>{error && <p className="vault-error" role="alert">{error}</p>}<Field ref={first} label="Título do item" value={value.title} maxLength={120} required disabled={pending} onChange={event => update("title", event.target.value)} /><Field as="select" label="Tipo do item" value={value.kind} disabled={pending} onChange={event => update("kind", event.target.value)}><option value="login">Login</option><option value="note">Nota segura</option></Field>{value.kind === "login" && <><Field label="Usuário do login" autoComplete="off" value={value.username} disabled={pending} onChange={event => update("username", event.target.value)} /><Field label="Senha do item" type="password" autoComplete="new-password" value={value.password} disabled={pending} onChange={event => update("password", event.target.value)} /><Field label="Endereço do login" value={value.url} disabled={pending} onChange={event => update("url", event.target.value)} /></>}<Field as="textarea" label="Nota privada" value={value.note} rows={5} disabled={pending} onChange={event => update("note", event.target.value)} /><p className="vault-hint">Título, tipo e todos os campos são cifrados antes do envio.</p></form></Drawer>;
}
