"use client";
import { useCallback, useEffect, useMemo, useRef, useState, useId, type FormEvent, type ChangeEvent } from "react";
import { DEMO_LOGOUT_EVENT, useDemoApplication } from "@/lib/demo/demo-provider";
import { prepareVault, unlockVault, recoverVault, changeMasterPassword, type VaultSession } from "@/core/cofre/crypto";
import type { VaultCipherItem, VaultInput, VaultPlainItem, VaultSnapshot } from "@/core/cofre/types";
import { cancelVaultDerivations, deriveVaultKey } from "@/adapters/crypto/argon2";
import { decodeVaultInput } from "@/core/cofre/validation";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Field } from "@/components/ui/field";
import { Icons } from "@/components/ui/icons";
import { ConfirmDialog } from "@/components/ui/dialog";
import { VaultEditor } from "./vault-editor";
import { vaultPortForApp } from "./vault-port";
import { createVaultClipboard, watchVaultActivity, watchVaultLogout } from "./vault-lifecycle";
import "./vault.css";
type Preparation = Awaited<ReturnType<typeof prepareVault>>;
type Readable = { item: VaultCipherItem; plain: VaultPlainItem | null };
export function VaultSkeleton() { return <div className="vault-skeleton" role="status" aria-label="Carregando Cofre"><i aria-hidden="true" /><i aria-hidden="true" /><i aria-hidden="true" /><i aria-hidden="true" /></div>; }
export function VaultWorkspace() {
 const app = useDemoApplication(), port = useMemo(() => vaultPortForApp(app), [app]), fileId = useId();
 const [state, setState] = useState<VaultSnapshot | null>(null), [readError, setReadError] = useState(""), [error, setError] = useState(""), [message, setMessage] = useState(""), [pending, setPending] = useState(false);
 const [session, setSession] = useState<VaultSession | null>(null), [preparation, setPreparation] = useState<Preparation | null>(null), [rows, setRows] = useState<Readable[]>([]), [mode, setMode] = useState<"recover" | "change" | null>(null), [trash, setTrash] = useState(false);
 const [password, setPassword] = useState(""), [nextPassword, setNextPassword] = useState(""), [confirm, setConfirm] = useState(""), [consent, setConsent] = useState(false), [partA, setPartA] = useState(""), [partB, setPartB] = useState(""), [downloadedA, setDownloadedA] = useState(false), [downloadedB, setDownloadedB] = useState(false), [proved, setProved] = useState(false);
 const [editor, setEditor] = useState<Readable | "new" | null>(null), [removing, setRemoving] = useState<Readable | null>(null), trigger = useRef<HTMLElement | null>(null);
 const liveSession = useRef<VaultSession | null>(null), livePreparation = useRef<Preparation | null>(null), generation = useRef(0), busy = useRef(false), retained = useRef<{ fingerprint: string; request: VaultInput } | null>(null);
 const clipboard = useRef<ReturnType<typeof createVaultClipboard> | null>(null);
 const refresh = useCallback(async () => { const snapshot = await port.snapshot(); setState(snapshot); setReadError(""); return snapshot; }, [port]);
 const lock = useCallback(() => { generation.current++; cancelVaultDerivations(); liveSession.current?.lock(); liveSession.current = null; livePreparation.current?.dispose(); livePreparation.current = null; setSession(null); setPreparation(null); setRows([]); setEditor(null); setRemoving(null); setMode(null); setPassword(""); setNextPassword(""); setConfirm(""); setPartA(""); setPartB(""); setConsent(false); setProved(false); setDownloadedA(false); setDownloadedB(false); retained.current = null; clipboard.current?.dispose(); setMessage("Cofre bloqueado."); }, []);
 useEffect(() => { let active = true; setState(null); void port.snapshot().then(value => { if (active) { setState(value); setReadError(""); } }, () => { if (active) setReadError("Não foi possível abrir os dados cifrados. Tente novamente."); }); return () => { active = false; lock(); }; }, [port, lock]);
 // Native kit file pickers blur the window; only an already unlocked session locks on blur.
 // Hidden tabs and inactivity always destroy the pending kit preparation and its raw bytes.
 useEffect(() => watchVaultActivity(lock, 300000, () => { if (liveSession.current?.unlocked) lock(); }), [lock]);
 useEffect(() => watchVaultLogout(DEMO_LOGOUT_EVENT, app.userId, lock), [app.userId, lock]);
 useEffect(() => { if (!session || !state) return; let active = true; void Promise.all(state.items.map(async item => { try { return { item, plain: await session.decrypt(item) }; } catch { return { item, plain: null }; } })).then(values => { if (active && session.unlocked) setRows(values); }); return () => { active = false; }; }, [session, state]);
 useEffect(() => { if (navigator.clipboard) clipboard.current = createVaultClipboard(navigator.clipboard, () => setError("Não foi possível limpar a área de transferência automaticamente. Use Limpar agora ou substitua o conteúdo no sistema.")); return () => { clipboard.current?.dispose(); clipboard.current = null; }; }, []);
 async function execute(command: VaultInput["command"], fields: Record<string, unknown>, revision: string) { const fingerprint = JSON.stringify({ command, fields, revision }); if (retained.current?.fingerprint !== fingerprint) retained.current = { fingerprint, request: decodeVaultInput({ command, input: { ...fields, expected_revision: revision, client_id: crypto.randomUUID() } }) }; await port.execute(retained.current.request); retained.current = null; return refresh(); }
 async function audit(operation: "unlocked" | "unlock_failed" | "locked" | "copied", snapshot: VaultSnapshot, itemId?: string) { return execute("vault.audit", { operation, ...(itemId ? { item_id: itemId } : {}) }, snapshot.revision); }
 async function run(action: (token: number) => Promise<void>) { if (busy.current) return; busy.current = true; setPending(true); setError(""); setMessage(""); const token = generation.current; try { await action(token); } catch (failure) { if (failure && typeof failure === "object" && "code" in failure && ["UNAUTHENTICATED", "FORBIDDEN", "SESSION_CHANGED"].includes(String(failure.code))) { lock(); setReadError("A sessão ou o acesso ao Cofre mudou. Reabra a página para continuar."); } else if (token === generation.current) setError(failure instanceof Error && /Cofre mudou|confirmação|kit|Kit|metade|Metade|Use ao menos|Preencha|limite|byte a byte/.test(failure.message) ? failure.message : "Não foi possível abrir ou proteger os dados. Confira a senha e as duas metades do kit, se usadas."); } finally { busy.current = false; setPending(false); setPassword(""); setNextPassword(""); setConfirm(""); } }
 function alive(token: number, key?: VaultSession) { if (token !== generation.current || document.visibilityState === "hidden") { key?.lock(); return false; } return true; }
 async function submit(event: FormEvent) { event.preventDefault(); if (!state) return; void run(async token => {
  if (mode === "recover") { if (nextPassword !== confirm) throw new Error("Preencha senhas iguais."); const current = await refresh(); if (!current.header) throw new Error(); const recovered = await recoverVault(current.header, partA, partB, nextPassword, deriveVaultKey); if (!alive(token, recovered.session)) return; try { await execute("vault.master.rewrap", { master: recovered.master }, current.revision); } catch (failure) { recovered.session.lock(); throw failure; } if (!alive(token, recovered.session)) return; liveSession.current = recovered.session; setSession(recovered.session); setMode(null); setPartA(""); setPartB(""); setMessage("Senha mestra recuperada. O kit antigo continua válido."); return; }
  if (mode === "change") { if (nextPassword !== confirm) throw new Error("Preencha senhas iguais."); const current = await refresh(); if (!current.header) throw new Error(); const master = await changeMasterPassword(current.header, password, nextPassword, deriveVaultKey); if (!alive(token)) return; await execute("vault.master.rewrap", { master }, current.revision); lock(); setMessage("Senha mestra alterada. Desbloqueie novamente. O kit antigo continua válido."); return; }
  if (!state.header) { if (!consent) throw new Error("Preencha a confirmação de irrecuperabilidade."); if (password !== confirm) throw new Error("Preencha senhas iguais."); const prepared = await prepareVault(app.userId, password, deriveVaultKey); if (!alive(token, prepared.session)) { prepared.dispose(); return; } livePreparation.current = prepared; setPreparation(prepared); setProved(false); return; }
  const current = await refresh(); if (!current.header) throw new Error(); let key: VaultSession; try { key = await unlockVault(current.header, password, deriveVaultKey); } catch { await audit("unlock_failed", current).catch(() => undefined); throw new Error(); } if (!alive(token, key)) return; try { await audit("unlocked", current); } catch (failure) { key.lock(); throw failure; } if (!alive(token, key)) return; liveSession.current = key; setSession(key);
 }); }
 async function completeCreation() { if (!preparation || !state) return; void run(async token => { if (!downloadedA || !downloadedB) throw new Error("Kit: baixe as duas metades antes de continuar."); if (!proved) { await preparation.prove(partA, partB); setProved(true); } if (!alive(token)) return; await execute("vault.create", { master: preparation.master, recovery: preparation.recovery, consent: true }, state.revision); if (!alive(token, preparation.session)) return; liveSession.current = preparation.session; livePreparation.current = null; setSession(preparation.session); setPreparation(null); setPartA(""); setPartB(""); setMessage("Cofre criado. O kit recuperou a chave original byte a byte."); }); }
 function download(half: "a" | "b") { if (!preparation) return; const blob = new Blob([preparation.kit[half]], { type: "text/plain;charset=utf-8" }), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = "segundo-cerebro-cofre-metade-" + half.toUpperCase() + ".txt"; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); if (half === "a") setDownloadedA(true); else setDownloadedB(true); }
 async function file(event: ChangeEvent<HTMLInputElement>, half: "a" | "b") { const selected = event.target.files?.[0], token = generation.current; if (!selected) return; if (selected.size > 1024) { setError("Metade do kit inválida: arquivo acima de 1 KiB."); return; } const value = await selected.text(); if (!alive(token)) return; if (half === "a") setPartA(value); else setPartB(value); setError(""); }
 // eslint-disable-next-line no-restricted-syntax -- Field excludes file inputs; this native recovery picker retains its labels, 16px controls, 44px targets and pending state.
 const kitFields = <>{(["a", "b"] as const).map(half => <label className="field vault-file" key={half} htmlFor={fileId + half}><span className="field__label">Arquivo da metade {half.toUpperCase()}</span><input id={fileId + half} className="field__control" type="file" accept=".txt,.json" disabled={pending} onChange={event => { void file(event, half); }} /></label>)}</>;
 if (readError) return <Card className="vault-message" data-access="allowed"><h2>Não foi possível abrir o Cofre</h2><p role="alert">{readError}</p><Button onClick={() => { void refresh().catch(() => setReadError("Não foi possível abrir os dados cifrados. Tente novamente.")); }}>Tentar de novo</Button></Card>;
 if (!state) return <VaultSkeleton />;
 return <div className="vault-workspace" data-access="allowed"><p className="vault-notice">{app.mode === "demo" ? "Demonstração com criptografia real e dados somente na memória desta visita. Use exemplos; recarregar apaga este Cofre." : "O conteúdo é cifrado neste navegador. A senha mestra e as duas metades do kit ficam sob seu controle."}</p>{error && <p className="vault-error" role="alert">{error}</p>}{message && <p className="vault-hint" role="status">{message}</p>}
 {preparation ? <Card className="vault-form-card"><h2>Guardar e provar o kit de recuperação</h2><p>Baixe as duas metades e guarde-as em locais diferentes. Uma metade sozinha não recupera a chave. Reabra os arquivos baixados para conferir a chave original byte a byte antes de criar o Cofre.</p><div className="vault-actions"><Button disabled={pending} onClick={() => download("a")}>Baixar metade A</Button><Button disabled={pending} onClick={() => download("b")}>Baixar metade B</Button></div>{kitFields}<Button variant="primary" loading={pending} disabled={!partA || !partB} onClick={() => { void completeCreation(); }}>Provar kit e criar Cofre</Button><Button disabled={pending} onClick={lock}>Descartar preparação</Button></Card>
 : session && mode !== "change" ? <Card className="vault-preview"><div className="vault-preview-heading"><h2>Cofre desbloqueado</h2><Button onClick={() => { const snapshot = state; lock(); void audit("locked", snapshot).catch(() => undefined); }}><Icons.Lock />Bloquear Cofre</Button></div><div className="vault-actions"><Button variant="primary" disabled={pending} onClick={event => { trigger.current = event.currentTarget; setEditor("new"); }}>Novo item</Button><Button disabled={pending} onClick={() => { setMode("change"); setError(""); }}>Trocar senha mestra</Button><Button disabled={pending} onClick={() => setTrash(!trash)}>{trash ? "Itens ativos" : "Lixeira do Cofre"}</Button></div>{rows.filter(row => trash ? row.item.deleted_at !== null : row.item.deleted_at === null).length ? <ul>{rows.filter(row => trash ? row.item.deleted_at !== null : row.item.deleted_at === null).map(row => <li key={row.item.id} className="vault-item"><div><strong>{row.plain?.title ?? "Item ilegível"}</strong><span>{row.plain ? row.plain.kind === "login" ? "Login" : "Nota segura" : "Não foi possível autenticar a cifra deste item."}</span></div><div className="vault-actions">{!row.plain ? <details><summary>Diagnosticar item ilegível</summary><p>Item {row.item.id}, versão {row.item.version}. A cifra pode ter sido alterada, trocada entre itens ou estar incompleta. O item foi preservado; recupere uma cópia válida.</p></details> : !trash && <><Button disabled={pending} aria-label={"Editar " + row.plain.title} onClick={event => { trigger.current = event.currentTarget; setEditor(row); }}>Editar</Button><Button disabled={pending || !clipboard.current} aria-label={"Copiar " + (row.plain.kind === "login" ? "senha de " : "nota de ") + row.plain.title} onClick={() => { void run(async token => { await clipboard.current?.copy(row.plain!.kind === "login" ? row.plain!.password : row.plain!.note); if (!alive(token)) return; await audit("copied", state, row.item.id); if (!alive(token)) return; setMessage("Copiado. A área de transferência será limpa em 30 segundos."); }); }}>Copiar</Button></>}{trash ? <Button disabled={pending} onClick={() => { void run(async () => { await execute("vault.item.restore", { id: row.item.id }, state.revision); }); }}>Restaurar {row.plain?.title ?? "item ilegível"}</Button> : <Button variant="ghost" disabled={pending} aria-label={"Excluir " + (row.plain?.title ?? "item ilegível")} onClick={event => { trigger.current = event.currentTarget; setRemoving(row); }}>Excluir</Button>}</div></li>)}</ul> : <p>{trash ? "A lixeira do Cofre está vazia." : "Nenhum item guardado. Crie seu primeiro login ou nota segura."}</p>}<p className="vault-hint">Bloqueio após 5 minutos sem atividade, ao ocultar a aba ou sair da janela. A limpeza do clipboard depende da permissão do navegador.</p><Button onClick={() => { void clipboard.current?.clear(); }}>Limpar área de transferência agora</Button></Card>
 : <Card className="vault-form-card"><Icons.Lock width={32} height={32} /><h2>{mode === "recover" ? "Recuperar Cofre pelo kit" : mode === "change" ? "Trocar senha mestra" : state.header ? "Cofre bloqueado" : "Criar Cofre"}</h2><form className="vault-form" onSubmit={submit}>{mode === "recover" ? kitFields : <Field type="password" label={mode === "change" ? "Senha mestra atual" : "Senha mestra"} value={password} autoComplete={state.header ? "current-password" : "new-password"} required disabled={pending} onChange={event => setPassword(event.target.value)} />}{(mode === "recover" || mode === "change") && <Field type="password" label="Nova senha mestra" value={nextPassword} autoComplete="new-password" required disabled={pending} onChange={event => setNextPassword(event.target.value)} />}{(!state.header || mode) && <Field type="password" label="Confirmar senha mestra" value={confirm} autoComplete="new-password" required disabled={pending} onChange={event => setConfirm(event.target.value)} hint="Use ao menos 10 caracteres com variedade, ou uma frase de 16 caracteres." />}{!state.header && <Button type="button" className="vault-consent" role="checkbox" aria-checked={consent} disabled={pending} onClick={() => setConsent(!consent)}><span className="vault-checkbox" aria-hidden="true">{consent && <Icons.Check />}</span>Entendo e assumo que perder a senha mestra e o kit torna meus dados irrecuperáveis. O servidor não pode recuperá-los.</Button>}<Button type="submit" variant="primary" loading={pending}>{mode === "recover" ? "Recuperar e trocar senha" : mode === "change" ? "Salvar nova proteção" : state.header ? "Desbloquear Cofre" : "Preparar Cofre e kit"}</Button></form>{state.header && <Button disabled={pending} variant="ghost" onClick={() => { setMode(mode ? null : "recover"); setError(""); setPassword(""); setNextPassword(""); setConfirm(""); setPartA(""); setPartB(""); }}>{mode ? "Voltar ao Cofre" : "Usar kit de recuperação"}</Button>}<p className="vault-hint">Trocar a senha mantém o kit antigo válido. Sem senha e sem as duas metades, os dados não podem ser recuperados.</p></Card>}
 {editor && session && <VaultEditor item={editor === "new" ? undefined : editor.item} plain={editor === "new" ? undefined : editor.plain ?? undefined} session={session} revision={state.revision} port={port} returnFocusRef={trigger} onClose={() => setEditor(null)} onSaved={async () => { await refresh(); setMessage("Item cifrado salvo."); }} onAccessLost={() => { lock(); setReadError("A sessão ou o acesso ao Cofre mudou. Reabra a página para continuar."); }} />}
 {removing && <ConfirmDialog open title="Excluir item do Cofre?" description="O item cifrado irá para a lixeira e poderá ser restaurado." confirmLabel="Mover item para a lixeira" loading={pending} returnFocusRef={trigger} onClose={() => setRemoving(null)} onConfirm={() => { void run(async () => { await execute("vault.item.delete", { id: removing.item.id }, state.revision); setRemoving(null); }); }} />}
 </div>;
}
