import { exigir } from "../contracts/base";
import type { VaultCipherItem, VaultEnvelope, VaultHeader, VaultKdf, VaultMasterWrap, VaultPlainItem } from "./types";
import { assertEnvelope, assertMaster, decodeBase64, encodeBase64, validatePlainItem } from "./validation";
export type VaultKdfPort = (password: Uint8Array<ArrayBuffer>, salt: Uint8Array<ArrayBuffer>, parameters: VaultKdf) => Promise<Uint8Array<ArrayBuffer>>;
const text = new TextEncoder();
const aad = (user: string, id: string, version: number) => text.encode(user + ":" + id + ":" + version);
const random = (size: number) => crypto.getRandomValues(new Uint8Array(size));
export function validateMasterPassword(value: string) { exigir(value.trim().length >= 10 && value.length <= 256 && new Set(value).size >= 6 && !/^[0-9\s]+$/.test(value) && (value.length >= 16 || [/[a-z]/, /[A-Z]/, /[0-9]/, /[^A-Za-z0-9]/].filter(rule => rule.test(value)).length >= 3) && !/^(password|senha|qwerty|123456)/i.test(value), "Use ao menos 10 caracteres com variedade, ou uma frase de 16 caracteres."); }
export async function importSessionKey(bytes: Uint8Array<ArrayBuffer>): Promise<CryptoKey> { exigir(bytes.byteLength === 32, "Material de chave inválido."); return crypto.subtle.importKey("raw", bytes, { name: "AES-GCM" }, false, ["encrypt", "decrypt"]); }
async function seal(key: CryptoKey, bytes: Uint8Array<ArrayBuffer>, context: Uint8Array<ArrayBuffer>): Promise<VaultEnvelope> { const iv = random(12); return { iv: encodeBase64(iv), ciphertext: encodeBase64(new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv, additionalData: context, tagLength: 128 }, key, bytes))) }; }
async function open(key: CryptoKey, envelope: VaultEnvelope, context: Uint8Array<ArrayBuffer>): Promise<Uint8Array<ArrayBuffer>> { assertEnvelope(envelope); return new Uint8Array(await crypto.subtle.decrypt({ name: "AES-GCM", iv: decodeBase64(envelope.iv), additionalData: context, tagLength: 128 }, key, decodeBase64(envelope.ciphertext))); }
async function passwordKey(password: string, kdf: VaultKdf, derive: VaultKdfPort) { const bytes = text.encode(password), salt = decodeBase64(kdf.salt); let derived: Uint8Array<ArrayBuffer> | undefined; try { derived = await derive(bytes, salt, kdf); return await importSessionKey(derived); } finally { if (bytes.byteLength) bytes.fill(0); salt.fill(0); derived?.fill(0); } }
async function wrapMaster(user: string, raw: Uint8Array<ArrayBuffer>, password: string, derive: VaultKdfPort): Promise<VaultMasterWrap> { validateMasterPassword(password); const kdf: VaultKdf = { algorithm: "argon2id", memory_kib: 65536, iterations: 3, parallelism: 1, salt: encodeBase64(random(16)) }; return { kdf, envelope: await seal(await passwordKey(password, kdf, derive), raw, aad(user, "master", 1)) }; }
export class VaultSession {
 #key: CryptoKey | null; #generation = 0;
 constructor(readonly userId: string, key: CryptoKey) { exigir(!key.extractable && key.algorithm.name === "AES-GCM", "Chave de sessão insegura."); this.#key = key; }
 get unlocked() { return this.#key !== null; }
 lock() { this.#generation++; this.#key = null; }
 async encrypt(id: string, version: number, value: VaultPlainItem) { const plain = validatePlainItem(value), key = this.#key, generation = this.#generation; exigir(key, "Desbloqueie o Cofre."); const bytes = text.encode(JSON.stringify(plain)); try { exigir(bytes.byteLength <= 32768, "O item deve ocupar até 32 KiB."); const result = await seal(key, bytes, aad(this.userId, id, version)); exigir(this.#key && generation === this.#generation, "O Cofre foi bloqueado durante a operação."); return result; } finally { bytes.fill(0); } }
 async decrypt(item: VaultCipherItem): Promise<VaultPlainItem> { const key = this.#key, generation = this.#generation; exigir(key && item.user_id === this.userId, "Desbloqueie o Cofre."); const bytes = await open(key, item.envelope, aad(this.userId, item.id, item.version)); try { exigir(this.#key && generation === this.#generation, "O Cofre foi bloqueado durante a operação."); return validatePlainItem(JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(bytes))); } finally { bytes.fill(0); } }
}
async function checksum(bytes: Uint8Array<ArrayBuffer>) { return encodeBase64(new Uint8Array(await crypto.subtle.digest("SHA-256", bytes))); }
async function kitPart(user: string, half: "A" | "B", bytes: Uint8Array<ArrayBuffer>) { return JSON.stringify({ format: "segundo-cerebro-vault-kit-1", user_id: user, half, data: encodeBase64(bytes), checksum: await checksum(bytes) }); }
async function parsePart(value: string, user: string, half: "A" | "B") { exigir(value.length <= 1024, "Metade do kit inválida."); let p: unknown; try { p = JSON.parse(value); } catch { throw new Error("Metade do kit inválida."); } exigir(p && typeof p === "object" && "format" in p && p.format === "segundo-cerebro-vault-kit-1" && "user_id" in p && p.user_id === user && "half" in p && p.half === half && "data" in p && typeof p.data === "string" && "checksum" in p && typeof p.checksum === "string", "Kit de outra conta ou metade incorreta."); const bytes = decodeBase64(p.data); try { exigir(bytes.length === 32 && await checksum(bytes) === p.checksum, "A metade do kit está incompleta ou foi alterada."); return bytes; } catch (error) { bytes.fill(0); throw error; } }
async function recoveryKey(user: string, a: string, b: string) { let left: Uint8Array<ArrayBuffer> | undefined, right: Uint8Array<ArrayBuffer> | undefined; const joined = new Uint8Array(32); try { left = await parsePart(a, user, "A"); right = await parsePart(b, user, "B"); for (let i = 0; i < 32; i++) joined[i] = left[i]! ^ right[i]!; return await importSessionKey(joined); } finally { left?.fill(0); right?.fill(0); joined.fill(0); } }
function equalBytes(a: Uint8Array, b: Uint8Array) { let difference = a.length ^ b.length; for (let i = 0; i < Math.max(a.length, b.length); i++) difference |= (a[i] ?? 0) ^ (b[i] ?? 0); return difference === 0; }
export async function prepareVault(user: string, password: string, derive: VaultKdfPort) {
 validateMasterPassword(password); const raw = random(32), recoveryRaw = random(32), left = random(32), right = new Uint8Array(32); let live = true;
 try {
  const master = await wrapMaster(user, raw, password, derive), recovery = await seal(await importSessionKey(recoveryRaw), raw, aad(user, "recovery", 1)), session = new VaultSession(user, await importSessionKey(raw));
  for (let i = 0; i < 32; i++) right[i] = recoveryRaw[i]! ^ left[i]!;
  const kit = { a: await kitPart(user, "A", left), b: await kitPart(user, "B", right) };
  return { master, recovery, session, kit,
   async prove(a: string, b: string) { exigir(live, "Esta preparação foi encerrada."); const recovered = await open(await recoveryKey(user, a, b), recovery, aad(user, "recovery", 1)); try { exigir(equalBytes(recovered, raw), "O kit não recuperou a chave original byte a byte."); live = false; raw.fill(0); return true; } finally { recovered.fill(0); } },
   dispose() { live = false; raw.fill(0); session.lock(); } };
 } catch (error) { raw.fill(0); throw error; } finally { recoveryRaw.fill(0); left.fill(0); right.fill(0); }
}
export async function unlockVault(header: VaultHeader, password: string, derive: VaultKdfPort): Promise<VaultSession> { assertMaster(header.master); const raw = await open(await passwordKey(password, header.master.kdf, derive), header.master.envelope, aad(header.user_id, "master", 1)); try { return new VaultSession(header.user_id, await importSessionKey(raw)); } finally { raw.fill(0); } }
export async function recoverVault(header: VaultHeader, a: string, b: string, password: string, derive: VaultKdfPort) { validateMasterPassword(password); const raw = await open(await recoveryKey(header.user_id, a, b), header.recovery, aad(header.user_id, "recovery", 1)); try { return { master: await wrapMaster(header.user_id, raw, password, derive), session: new VaultSession(header.user_id, await importSessionKey(raw)) }; } finally { raw.fill(0); } }
export async function changeMasterPassword(header: VaultHeader, current: string, next: string, derive: VaultKdfPort) { validateMasterPassword(next); const raw = await open(await passwordKey(current, header.master.kdf, derive), header.master.envelope, aad(header.user_id, "master", 1)); try { return await wrapMaster(header.user_id, raw, next, derive); } finally { raw.fill(0); } }
