import { exigir, instanteValido } from "../contracts/base";
import type { VaultEnvelope, VaultInput, VaultMasterWrap, VaultPlainItem, VaultSnapshot } from "./types";
const record = (v: unknown): v is Record<string, unknown> => v !== null && typeof v === "object" && !Array.isArray(v);
const exact = (v: Record<string, unknown>, keys: string[]) => Object.keys(v).every(key => keys.includes(key)) && keys.every(key => Object.hasOwn(v, key));
export function decodeBase64(v: string): Uint8Array<ArrayBuffer> { exigir(/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(v), "Envelope cifrado inválido."); const raw = atob(v); const bytes = Uint8Array.from(raw, c => c.charCodeAt(0)); exigir(btoa(raw) === v, "Envelope cifrado inválido."); return bytes; }
export function encodeBase64(v: Uint8Array): string { let raw = ""; for (const byte of v) raw += String.fromCharCode(byte); return btoa(raw); }
export function assertEnvelope(v: unknown, wrapped = false): asserts v is VaultEnvelope {
 exigir(record(v) && exact(v, ["iv", "ciphertext"]) && typeof v.iv === "string" && typeof v.ciphertext === "string" && v.ciphertext.length <= 65536, "Envelope cifrado inválido.");
 exigir(decodeBase64(v.iv).length === 12 && (wrapped ? decodeBase64(v.ciphertext).length === 48 : decodeBase64(v.ciphertext).length >= 16 && decodeBase64(v.ciphertext).length <= 49152), "Envelope cifrado inválido.");
}
export function assertMaster(v: unknown): asserts v is VaultMasterWrap { exigir(record(v) && exact(v, ["kdf", "envelope"]) && record(v.kdf) && exact(v.kdf, ["algorithm", "memory_kib", "iterations", "parallelism", "salt"]) && v.kdf.algorithm === "argon2id" && v.kdf.memory_kib === 65536 && v.kdf.iterations === 3 && v.kdf.parallelism === 1 && typeof v.kdf.salt === "string" && decodeBase64(v.kdf.salt).length === 16, "Parâmetros de proteção inválidos."); assertEnvelope(v.envelope, true); }
export function decodeVaultInput(v: unknown): VaultInput {
 exigir(record(v) && exact(v, ["command", "input"]) && typeof v.command === "string" && record(v.input), "Operação do Cofre inválida."); const input = v.input;
 const fields: Record<string, string[]> = { "vault.create": ["master", "recovery", "consent"], "vault.master.rewrap": ["master"], "vault.item.create": ["id", "version", "envelope"], "vault.item.update": ["id", "version", "envelope"], "vault.item.delete": ["id"], "vault.item.restore": ["id"], "vault.audit": ["operation"] };
 const keys = fields[v.command]; exigir(keys && Object.keys(input).every(key => [...keys, "client_id", "expected_revision", ...(v.command === "vault.audit" ? ["item_id"] : [])].includes(key)) && [...keys, "client_id", "expected_revision"].every(key => Object.hasOwn(input, key)), "Campos da operação do Cofre inválidos.");
 exigir(typeof input.client_id === "string" && /^[A-Za-z0-9_-]{1,200}$/.test(input.client_id) && typeof input.expected_revision === "string" && /^(0|[1-9][0-9]*)$/.test(input.expected_revision), "Identidade da operação inválida.");
 if (input.master !== undefined) assertMaster(input.master); if (input.recovery !== undefined) assertEnvelope(input.recovery, true);
 if (v.command === "vault.create") exigir(input.consent === true, "Confirme a consequência de perder senha e kit.");
 if (input.id !== undefined) exigir(typeof input.id === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(input.id), "Item inválido.");
 if (input.version !== undefined) { exigir(Number.isSafeInteger(input.version) && Number(input.version) >= 1 && Number(input.version) <= 2147483647, "Versão inválida."); assertEnvelope(input.envelope); }
 if (v.command === "vault.audit") { exigir(["unlocked", "unlock_failed", "locked", "copied"].includes(String(input.operation)), "Operação de auditoria inválida."); exigir(input.item_id === undefined || typeof input.item_id === "string" && /^[0-9a-f-]{36}$/i.test(input.item_id), "Item de auditoria inválido."); exigir(input.operation === "copied" ? input.item_id !== undefined : input.item_id === undefined, "Auditoria fora da operação."); }
 return structuredClone(v) as VaultInput;
}
export function assertVaultSnapshot(v: unknown, userId: string): asserts v is VaultSnapshot {
 exigir(record(v) && exact(v, ["revision", "header", "items"]) && typeof v.revision === "string" && /^(0|[1-9][0-9]*)$/.test(v.revision) && Array.isArray(v.items) && v.items.length <= 500 && JSON.stringify(v).length <= 8388608, "Leitura completa do Cofre indisponível.");
 if (v.header !== null) { const h = v.header; exigir(record(h) && exact(h, ["user_id", "schema_version", "master", "recovery", "consent_at", "created_at", "updated_at"]) && h.user_id === userId && h.schema_version === 1 && [h.consent_at, h.created_at, h.updated_at].every(x => typeof x === "string" && instanteValido(x)), "Cabeçalho do Cofre inválido."); assertMaster(h.master); assertEnvelope(h.recovery, true); }
 const ids = new Set<string>(); for (const item of v.items) { exigir(record(item) && exact(item, ["id", "user_id", "version", "envelope", "deleted_at", "created_at", "updated_at"]) && typeof item.id === "string" && !ids.has(item.id) && item.user_id === userId && Number.isSafeInteger(item.version) && Number(item.version) >= 1 && [item.created_at, item.updated_at].every(x => typeof x === "string" && instanteValido(x)) && (item.deleted_at === null || typeof item.deleted_at === "string" && instanteValido(item.deleted_at)) && record(item.envelope) && exact(item.envelope, ["iv", "ciphertext"]) && typeof item.envelope.iv === "string" && item.envelope.iv.length <= 24 && typeof item.envelope.ciphertext === "string" && item.envelope.ciphertext.length <= 65536, "Item cifrado inválido."); ids.add(item.id); }
 exigir(v.header !== null || v.items.length === 0, "Itens sem cabeçalho de proteção.");
}
export function validatePlainItem(v: unknown): VaultPlainItem { exigir(record(v) && exact(v, ["title", "kind", "username", "password", "url", "note"]) && typeof v.title === "string" && v.title.trim().length > 0 && v.title.length <= 120 && ["login", "note"].includes(String(v.kind)) && [v.username, v.password, v.url, v.note].every(x => typeof x === "string") && JSON.stringify(v).length <= 32768, "Preencha um título e conteúdo de até 32 KiB."); return { title: v.title.trim(), kind: v.kind === "login" ? "login" : "note", username: String(v.username), password: String(v.password), url: String(v.url), note: String(v.note) }; }
