import { describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { adminCommitment, createAdminAuthPort, createAdminPort, parseAdminOperation, type AdminRpc } from "../../src/adapters/db/admin-runtime";
import type { AdminOperation, AdminPort } from "../../src/core/admin";
import { AdminAuthUncertainError } from "../../src/core/admin";
import type { SupabaseAuthConfig } from "../../src/lib/auth/config";
const actor = "10000000-0000-4000-8000-000000000001", target = "10000000-0000-4000-8000-000000000002", id = "10000000-0000-4000-8000-000000000003", session = "10000000-0000-4000-8000-000000000004";
const operation: AdminOperation = { operation_id: id, client_id: "original", actor_user_id: actor, target_user_id: target, command: "admin.user.create", phase: "reserved", role: null, feature_key: null, allowed: null, created_at: "2026-10-09T12:00:00Z", updated_at: "2026-10-09T12:00:00Z" };
const identity = { userId: actor, sessionId: session, mustChangePassword: false, role: "master" as const, entitlements: {} };
const config: SupabaseAuthConfig = { mode: "supabase", supabaseUrl: "https://rishenjoikgmfubmnfiu.supabase.co", appOrigin: "http://127.0.0.1:3000", publishableKey: "public", secretKey: "service", stateSecret: "state".repeat(10), rateLimitSecret: "limit".repeat(10), secureCookies: false };
function sdkFixture() {
 const log: string[] = [], port = { guard: vi.fn(async () => { log.push("guard"); return structuredClone(operation); }) } as unknown as AdminPort;
 const admin = {
  getUserById: vi.fn(async () => { log.push("read"); return { data: { user: null }, error: { status: 404, code: "user_not_found" } }; }),
  createUser: vi.fn(async () => { log.push("create"); return { data: { user: { id: target, app_metadata: { sc_admin_operation: id } } }, error: null }; }),
  updateUserById: vi.fn(async () => { log.push("update"); return { data: { user: { id: target } }, error: null }; }),
 };
 const client = { auth: { admin } } as unknown as Parameters<typeof createAdminAuthPort>[1];
 return { port, admin, auth: createAdminAuthPort(port, client), log };
}
describe("Admin authored server RPC contract", () => {
 it("binds actor, current session and private execution UUID only from server", async () => { const rpc = vi.fn<AdminRpc>(async () => ({ data: operation, error: null })), port = createAdminPort(identity, rpc, id); await port.reserve({ command: operation.command, client_id: "original", commitment: "a".repeat(64) }); expect(rpc).toHaveBeenCalledWith("admin_reserve", { p_actor: actor, p_session: session, p_execution: id, p_intent: { command: operation.command, client_id: "original", commitment: "a".repeat(64) } }); });
 it("current SQL guard is consulted even when cached identity says master", async () => { const rpc = vi.fn<AdminRpc>(async () => ({ data: null, error: { code: "42501" } })); await expect(createAdminPort(identity, rpc).requireMaster()).rejects.toMatchObject({ code: "forbidden" }); expect(rpc).toHaveBeenCalledWith("admin_snapshot", expect.objectContaining({ p_actor: actor })); });
 it.each([{ ...identity, role: "user" as const }, { ...identity, mustChangePassword: true }, { ...identity, entitlements: { admin: false } }])("cached policy denies before privileged RPC %#", async denied => { const rpc = vi.fn<AdminRpc>(); await expect(createAdminPort(denied, rpc).requireMaster()).rejects.toMatchObject({ code: "forbidden" }); expect(rpc).not.toHaveBeenCalled(); });
 it.each(["23505", "40001"])("maps conflict %s without server payloads", async code => { const rpc: AdminRpc = async () => ({ data: null, error: { code } }); await expect(createAdminPort(identity, rpc).guard(id)).rejects.toMatchObject({ code: "CONFLICT" }); });
 it("unknown DB errors fail closed and cannot leak SQL details", async () => { const rpc: AdminRpc = async () => { throw new Error("password-secret-SQL"); }; await expect(createAdminPort(identity, rpc).guard(id)).rejects.toMatchObject({ code: "unavailable" }); });
 it.each([{ commitment: "private" }, { password: "private" }, { role: "root" }, { feature_key: "root" }, { allowed: "true" }, { updated_at: "bad" }, { target_user_id: "not-uuid" }])("rejects extra/private or malformed operation data %#", patch => { expect(() => parseAdminOperation({ ...operation, ...patch })).toThrow(); });
 it("does not accept a substituted operation or owner in RPC result", async () => { const rpc: AdminRpc = async () => ({ data: { ...operation, operation_id: target }, error: null }); await expect(createAdminPort(identity, rpc).guard(id)).rejects.toMatchObject({ code: "unavailable" }); });
 it("snapshot includes only named user/audit metadata", async () => { const rpc: AdminRpc = async () => ({ data: { users: [], audit: [], operations: [operation] }, error: null }); expect(await createAdminPort(identity, rpc).snapshot()).toEqual({ users: [], audit: [], operations: [operation] }); const leak: AdminRpc = async () => ({ data: { users: [], audit: [], operations: [], tasks: [{ text: "private" }] }, error: null }); await expect(createAdminPort(identity, leak).snapshot()).rejects.toMatchObject({ code: "unavailable" }); });
 it("snapshot rejects raw Auth metadata and credential fields in users", async () => { const user = { user_id: target, email: "p@example.invalid", created_at: operation.created_at, last_sign_in_at: null, role: "user", status: "blocked", must_change_password: true, admin_allowed: true, active_sessions: 0, pending_operation: id, raw_app_meta_data: { role: "master" } }; const rpc: AdminRpc = async () => ({ data: { users: [user], audit: [], operations: [] }, error: null }); await expect(createAdminPort(identity, rpc).snapshot()).rejects.toMatchObject({ code: "unavailable" }); });
});
describe("Keyed administrative commitment", () => {
 it("is stable across object key order and distinct for changed credentials", () => { const commit = adminCommitment(config, { ADMIN_COMMAND_SECRET: "admin".repeat(10) }); const a = commit({ command: "create", password: "private", email: "a@example.invalid" }); expect(a).toMatch(/^[a-f0-9]{64}$/); expect(commit({ email: "a@example.invalid", password: "private", command: "create" })).toBe(a); expect(commit({ command: "create", password: "changed", email: "a@example.invalid" })).not.toBe(a); expect(a).not.toContain("private"); });
 it.each([undefined, "short", config.secretKey, config.stateSecret, config.rateLimitSecret])("requires a separate >=32-byte admin secret %#", secret => { expect(() => adminCommitment(config, { ADMIN_COMMAND_SECRET: secret })).toThrow(); });
});
describe("Auth SDK saga uses the exact guarded target", () => {
 it("creates only reserved UUID, metadata marker, default role and initially banned Auth user", async () => { const f = sdkFixture(); await f.auth.create(operation, "p@example.invalid", "Temporary private 123"); expect(f.log).toEqual(["guard", "read", "guard", "create"]); expect(f.admin.createUser).toHaveBeenCalledWith({ id: target, email: "p@example.invalid", password: "Temporary private 123", email_confirm: true, ban_duration: "876000h", app_metadata: { sc_admin_operation: id } }); expect(JSON.stringify(vi.mocked(f.admin.createUser).mock.calls)).not.toContain("role"); });
 it("unknown creation response stays uncertain; exact marker skips duplicate create after operational clearance", async () => { const f = sdkFixture(); vi.mocked(f.admin.createUser).mockResolvedValueOnce({ data: { user: { id: actor, app_metadata: { sc_admin_operation: id } } }, error: null }); await expect(f.auth.create(operation, "p@example.invalid", "Temporary private 123")).rejects.toBeInstanceOf(AdminAuthUncertainError); vi.mocked(f.admin.getUserById).mockResolvedValue({ data: { user: { id: target, app_metadata: { sc_admin_operation: id } } } as never, error: null as never }); expect(await f.auth.verifyCreated(operation)).toBe(true); await f.auth.create(operation, "p@example.invalid", "Temporary private 123"); expect(f.admin.createUser).toHaveBeenCalledTimes(1); });
 it("an editable role marker never grants authority or substitutes operation identity", async () => { const f = sdkFixture(); vi.mocked(f.admin.getUserById).mockResolvedValue({ data: { user: { id: target, app_metadata: { role: "master", sc_admin_operation: actor } } } as never, error: null as never }); await expect(f.auth.verifyCreated(operation)).rejects.toMatchObject({ code: "CONFLICT" }); expect(f.admin.createUser).not.toHaveBeenCalled(); expect(f.admin.updateUserById).not.toHaveBeenCalled(); });
 it("denied current guard prevents even an Auth read", async () => { const f = sdkFixture(); vi.mocked(f.port.guard).mockRejectedValue(new Error("revoked master")); await expect(f.auth.create(operation, "p@example.invalid", "Temporary private 123")).rejects.toThrow("revoked"); expect(f.admin.getUserById).not.toHaveBeenCalled(); expect(f.admin.createUser).not.toHaveBeenCalled(); });
 it("a forged target on a valid operation ID never reaches the Auth SDK", async () => { const f = sdkFixture(); await expect(f.auth.create({ ...operation, target_user_id: actor }, "p@example.invalid", "Temporary private 123")).rejects.toMatchObject({ code: "CONFLICT" }); expect(f.admin.getUserById).not.toHaveBeenCalled(); await expect(f.auth.ban({ ...operation, target_user_id: actor }, true)).rejects.toMatchObject({ code: "CONFLICT" }); expect(f.admin.updateUserById).not.toHaveBeenCalled(); });
 it("completed operation cannot mutate Auth", async () => { const f = sdkFixture(); vi.mocked(f.port.guard).mockResolvedValue({ ...operation, phase: "complete" }); await expect(f.auth.create(operation, "p@example.invalid", "Temporary private 123")).rejects.toMatchObject({ code: "CONFLICT" }); expect(f.admin.createUser).not.toHaveBeenCalled(); });
 it("revalidates immediately before both ban and unban", async () => { const f = sdkFixture(), block = { ...operation, command: "admin.user.block" as const }; vi.mocked(f.port.guard).mockResolvedValue(block); await f.auth.ban(block, true); expect(f.log).toEqual(["update"]); expect(f.port.guard).toHaveBeenCalledTimes(2); expect(f.admin.updateUserById).toHaveBeenCalledWith(target, { ban_duration: "876000h" }); const unban = { ...operation, command: "admin.user.unblock" as const }; vi.mocked(f.port.guard).mockResolvedValue(unban); await f.auth.ban(unban, false); expect(f.admin.updateUserById).toHaveBeenLastCalledWith(target, { ban_duration: "none" }); });
 it("SQL revocation is used instead of passing a user UUID to signOut(JWT)", async () => { const f = sdkFixture(); expect("signOut" in f.admin).toBe(false); expect(await f.auth.verifyCreated(operation)).toBe(false); });
 it("transport rejection may leave an Auth mutation in flight and never counts as terminal proof", async () => { const f = sdkFixture(); vi.mocked(f.admin.createUser).mockRejectedValue(new Error("network timeout")); await expect(f.auth.create(operation, "p@example.invalid", "Temporary private 123")).rejects.toBeInstanceOf(AdminAuthUncertainError); });
 it.each([0, 500, 503])("ambiguous provider status %s keeps the claim", async status => { const f = sdkFixture(); vi.mocked(f.admin.createUser).mockResolvedValue({ data: { user: null } as never, error: { status } as never }); await expect(f.auth.create(operation, "p@example.invalid", "Temporary private 123")).rejects.toBeInstanceOf(AdminAuthUncertainError); });
 it("explicit Auth validation response is terminated and reveals no raw provider message", async () => { const f = sdkFixture(); vi.mocked(f.admin.createUser).mockResolvedValue({ data: { user: null } as never, error: { status: 422 } as never }); await expect(f.auth.create(operation, "p@example.invalid", "Temporary private 123")).rejects.toMatchObject({ code: "unavailable" }); });
 it("execution UUID cannot escape the allowlisted operation DTO", () => { expect(() => parseAdminOperation({ ...operation, active_execution: id })).toThrow(); });
});
