import { describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { createCalendarRepository, parseCalendarRun, parseCalendarSnapshot, parsePrivateCalendarAccount, type CalendarRpc } from "../../src/adapters/db/google-calendar-runtime";
const owner = "25000000-0000-4000-8000-000000000001", session = "25000000-0000-4000-8000-000000000002", execution = "25000000-0000-4000-8000-000000000003", account = "25000000-0000-4000-8000-000000000004", source = "25000000-0000-4000-8000-000000000005";
const snapshot = { accounts: [{ id: account, user_id: owner, email: "x@example.invalid", scopes: ["openid"], status: "connected", last_synced_at: null }], calendars: [{ id: source, user_id: owner, account_id: account, name: "Work", color_key: "calendar", selected: true }], items: [], sync_runs: [], window: null, preferences: { default_calendar_view: "month", meeting_reminders_enabled: true, meeting_reminder_minutes: 10 } };
describe("Calendar DTO strict owner and private protocol", () => {
 it("safe snapshot cannot contain token, code or foreign owner fields", () => { expect(parseCalendarSnapshot(snapshot, owner)).toEqual(snapshot); for (const patch of [{ tokens: {} }, { code: "private" }, { accounts: [{ ...snapshot.accounts[0], user_id: session }] }, { preferences: { ...snapshot.preferences, refresh_token: "private" } }]) expect(() => parseCalendarSnapshot({ ...snapshot, ...patch }, owner)).toThrow(); });
 it("visible event must belong to selected source and connected owner account", () => { const event = { id: execution, user_id: owner, account_id: account, calendar_id: source, title: "Meeting", starts_at: "2026-10-09T12:00:00Z", ends_at: "2026-10-09T13:00:00Z", location: null, linked_capture_id: null, habit_id: null, all_day: false, html_link: null, reminder_minutes: 10 }; expect(parseCalendarSnapshot({ ...snapshot, items: [event] }, owner).items).toHaveLength(1); expect(() => parseCalendarSnapshot({ ...snapshot, calendars: [{ ...snapshot.calendars[0], selected: false }], items: [event] }, owner)).toThrow(); expect(() => parseCalendarSnapshot({ ...snapshot, accounts: [{ ...snapshot.accounts[0], status: "reauthorize" }], items: [event] }, owner)).toThrow(); });
 it("private metadata rejects wrong owner or unexpected raw token fields", () => { expect(() => parsePrivateCalendarAccount({ id: account, user_id: session }, owner)).toThrow(); expect(() => parseCalendarRun({ id: execution, user_id: owner, access_token: "private" })).toThrow(); });
 it("binds all commands to server identity/session and private execution UUID", async () => { const rpc = vi.fn<CalendarRpc>(async () => ({ data: {}, error: null })), repo = createCalendarRepository(owner, session, rpc, { execution }); await repo.select(source, false, "client"); expect(rpc).toHaveBeenCalledWith({ p_user: owner, p_session: session, p_cron: false, p_execution: execution, p_command: "select", p_input: { calendar_id: source, selected: false, client_id: "client" } }); });
 it.each(["42501", "40001", "23503", "PT429", "22023", "XX000"])("maps SQL error %s without raw data exposure", async code => { const rpc = vi.fn<CalendarRpc>(async () => ({ data: "secret-canary", error: { code } })), repo = createCalendarRepository(owner, session, rpc, { execution }); await expect(repo.requireAccess()).rejects.toThrow(); await expect(repo.requireAccess()).rejects.not.toThrow("secret-canary"); });
 it("rejects invalid cron or session identities before issuing any RPC", () => { const rpc = vi.fn(); expect(() => createCalendarRepository(owner, null, rpc)).toThrow(); expect(() => createCalendarRepository(owner, session, rpc, { cron: true })).toThrow(); expect(rpc).not.toHaveBeenCalled(); });
});
