import { describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { createVaultGateway, type VaultRpc } from "../../src/adapters/db/vault-gateway";
import { encodeBase64 } from "../../src/core/cofre/validation";
import type { VaultInput } from "../../src/core/cofre/types";
const user = "11111111-1111-4111-8111-111111111111", session = "22222222-2222-4222-8222-222222222222", id = "33333333-3333-4333-8333-333333333333";
const request: VaultInput = { command: "vault.item.create", input: { client_id: "test", expected_revision: "0", id, version: 1, envelope: { iv: encodeBase64(new Uint8Array(12)), ciphertext: encodeBase64(new Uint8Array(48)) } } };
const commit = { request, metadata: { id, user_id: user, operation: "item_created" as const, version: 1, occurred_at: "2026-10-09T12:00:00Z" }, event_id: session, occurred_at: "2026-10-09T12:00:00Z", canal: "web" as const };
describe("T024 service-only cipher gateway", () => {
 it("every RPC derives verified owner, session and operation; wire carries cipher and metadata only", async () => { const rpc = vi.fn<VaultRpc>().mockResolvedValue({ data: { id, revision: "3" }, error: null }); const gateway = createVaultGateway(user, session, request.command, rpc); await gateway.commit(commit); expect(rpc).toHaveBeenCalledWith("vault_commit", { p_user: user, p_session: session, p_operation: request.command, p_request: commit }); const wire = JSON.stringify(rpc.mock.calls); expect(wire).not.toMatch(/password|username|title|kit/); });
 it("unknown outcome and malformed response reconcile the exact same request", async () => { const rpc = vi.fn<VaultRpc>().mockRejectedValueOnce(new Error("network-private")).mockResolvedValueOnce({ data: { id, revision: "3" }, error: null }); const gateway = createVaultGateway(user, session, request.command, rpc); expect(await gateway.commit(commit)).toEqual({ id, revision: "3" }); expect(rpc.mock.calls[1]).toEqual(["vault_receipt", { p_user: user, p_session: session, p_operation: request.command, p_request: request }]); const malformed = vi.fn<VaultRpc>().mockResolvedValueOnce({ data: { payload: "private" }, error: null }).mockResolvedValueOnce({ data: { id, revision: "3" }, error: null }); expect(await createVaultGateway(user, session, request.command, malformed).commit(commit)).toEqual({ id, revision: "3" }); });
 it("forbidden and conflicts fail without exposing provider messages", async () => { const rpc = vi.fn<VaultRpc>().mockResolvedValue({ data: null, error: { code: "42501" } }); await expect(createVaultGateway(user, session, request.command, rpc).commit(commit)).rejects.toMatchObject({ code: "forbidden" }); expect(rpc).toHaveBeenCalledTimes(1); rpc.mockResolvedValue({ data: null, error: { code: "40001" } }); await expect(createVaultGateway(user, session, request.command, rpc).commit(commit)).rejects.toMatchObject({ code: "CONFLICT" }); });
 it("foreign owner and incomplete snapshots fail closed", async () => { const rpc = vi.fn<VaultRpc>().mockResolvedValue({ data: { revision: "0", header: null, items: [{ user_id: session }] }, error: null }); await expect(createVaultGateway(user, session, "read.vault", rpc).snapshot()).rejects.toThrow(); rpc.mockResolvedValue({ data: { revision: "0", items: [] }, error: null }); await expect(createVaultGateway(user, session, "read.vault", rpc).snapshot()).rejects.toThrow(); });
});
