import "server-only";
import { randomUUID,createHash } from "node:crypto";
import { createPrivilegedClient } from "../../lib/auth/clients";
import type { SupabaseAuthConfig } from "../../lib/auth/config";
import { AuthGuardError,type AuthenticatedIdentity } from "../../lib/auth/types";
import { ErroDeDominio,exigir } from "../../core/contracts/base";
import { nomeSeguroArquivo,type Arquivo,type ReservaUpload,type SnapshotDrive,type TipoArquivo } from "../../core/drive";
import { FilesCommitUnknown,type DriveGateway } from "./files-store";
import { readFilePolicy } from "./files-policy";
import { prepararArquivo } from "./files-processor";
export const STAGING_BUCKET="second-brain-staging",FINAL_BUCKET="second-brain-files";
type Rpc=(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:{code?:string}|null}>;
const object=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==="object"&&!Array.isArray(value);
export function filesServicesForRequest(config:SupabaseAuthConfig,actor:AuthenticatedIdentity){
 if(config.supabaseUrl!=="https://rishenjoikgmfubmnfiu.supabase.co")throw new AuthGuardError("unavailable");const client=createPrivilegedClient(config),policy=readFilePolicy();const rpc=client.rpc as unknown as Rpc;
 const bound={p_user:actor.userId,p_session:actor.sessionId};
 const verifiedFile=(value:unknown,id:string):Arquivo=>{exigir(object(value)&&value.user_id===actor.userId&&value.id===id&&["drive","capture_image","avatar"].includes(String(value.kind))&&typeof value.name==="string"&&typeof value.mime==="string"&&Number.isSafeInteger(value.bytes)&&Number(value.bytes)>0&&typeof value.sha256==="string"&&/^[a-f0-9]{64}$/.test(value.sha256),"Resposta do arquivo inválida.");return value as unknown as Arquivo;};
 async function call(name:string,args:Record<string,unknown>,write=false){let reply:Awaited<ReturnType<Rpc>>;try{reply=await rpc(name,{...args,...bound});}catch{if(write)throw new FilesCommitUnknown();throw new AuthGuardError("unavailable");}if(reply.error){const code=reply.error.code;if(code==="42501")throw new AuthGuardError("forbidden");if(code==="PT429")throw new ErroDeDominio("CONFLICT","Aguarde antes de tentar outro envio.");if(["22023","23514","23503"].includes(code??""))throw new ErroDeDominio("VALIDATION","Revise o arquivo, seu destino e o espaço disponível.");if(["23505","40001"].includes(code??""))throw new ErroDeDominio("CONFLICT","O arquivo mudou. Atualize os dados e confirme o mesmo envio.");if(write&&!code)throw new FilesCommitUnknown();throw new AuthGuardError("unavailable");}return reply.data;}
 const services={
  gateway(operation:string):DriveGateway{return{actorId:actor.userId,snapshot:async()=>await call("drive_snapshot",{p_operation:operation,p_quota:policy.quota_bytes,p_max_bytes:policy.drive_max_bytes}) as SnapshotDrive,
   commit:async request=>await call("drive_commit",{p_operation:operation,p_request:request},true) as Awaited<ReturnType<DriveGateway["commit"]>>,receipt:async(command,clientId)=>await call("drive_receipt",{p_operation:operation,p_command:command,p_client_id:clientId}) as Awaited<ReturnType<DriveGateway["receipt"]>>};},
  async reserve(kind:TipoArquivo,name:string,folderId:string|null,clientId:string){name=nomeSeguroArquivo(name);const uploadId=randomUUID();const reservation=await call("file_upload_reserve",{p_kind:kind,p_name:name,p_folder:folderId,p_client_id:clientId,p_upload:uploadId,p_max_bytes:kind==="drive"?policy.drive_max_bytes:policy.image_max_bytes,p_quota:policy.quota_bytes,p_expires:new Date(Date.now()+150*60*1000).toISOString()},true) as ReservaUpload;
   exigir(reservation.user_id===actor.userId&&reservation.staging_path===`${actor.userId}/${reservation.id}`&&reservation.kind===kind,"Reserva inválida.");
   const signed=await client.storage.from(STAGING_BUCKET).createSignedUploadUrl(reservation.staging_path,{upsert:false});if(signed.error||!signed.data)throw new AuthGuardError("unavailable");
   return{id:reservation.id,upload_url:signed.data.signedUrl,token:signed.data.token,expires_at:reservation.expires_at};},
  async finalize(uploadId:string,clientId:string):Promise<Arquivo>{const lease=randomUUID();const claimed=await call("file_upload_claim",{p_upload:uploadId,p_lease:lease,p_client_id:clientId},true) as {reservation:ReservaUpload;file:Arquivo|null};if(claimed.file)return verifiedFile(claimed.file,uploadId);const reservation=claimed.reservation;
   exigir(reservation.user_id===actor.userId&&reservation.id===uploadId&&reservation.staging_path===`${actor.userId}/${uploadId}`&&reservation.final_path===`${actor.userId}/${uploadId}`,"Reserva inválida.");
   try { const download=await client.storage.from(STAGING_BUCKET).download(reservation.staging_path);if(download.error||!download.data)throw new ErroDeDominio("VALIDATION","Conclua o envio antes de finalizar.");exigir(download.data.size<=reservation.max_bytes,"Arquivo excede o limite real.");
   const prepared=await prepararArquivo(reservation.kind,reservation.name,new Uint8Array(await download.data.arrayBuffer()),policy);
   const published=await client.storage.from(FINAL_BUCKET).upload(reservation.final_path,prepared.bytes,{contentType:prepared.mime,upsert:false,cacheControl:"0"});
   if(published.error){const existing=await client.storage.from(FINAL_BUCKET).download(reservation.final_path);if(existing.error||!existing.data||existing.data.size!==prepared.bytes.byteLength||createHash("sha256").update(new Uint8Array(await existing.data.arrayBuffer())).digest("hex")!==prepared.sha256)throw new AuthGuardError("unavailable");}
   const now=new Date().toISOString();const metadata:Arquivo={id:uploadId,user_id:actor.userId,kind:reservation.kind,folder_id:reservation.folder_id,name:prepared.name,mime:prepared.mime,bytes:prepared.bytes.byteLength,sha256:prepared.sha256,width:prepared.width,height:prepared.height,starred:false,deleted_at:null,deletion_batch_id:null,created_at:now,updated_at:now,modified_at:now};
   try{return verifiedFile(await call("file_upload_complete",{p_upload:uploadId,p_lease:lease,p_client_id:clientId,p_file:metadata,p_quota:policy.quota_bytes},true),uploadId);}catch(error){if(error instanceof FilesCommitUnknown){const row=await call("file_upload_status",{p_upload:uploadId});if(object(row)&&object(row.file))return verifiedFile(row.file,uploadId);}throw error;}
   } catch(error) { try { await call("file_upload_release",{p_upload:uploadId,p_lease:lease},true); } catch { /* Original failure and immutable orphan are reconciled by cleanup. */ } throw error; }
  },
  async signedRead(id:string,download=false){const metadata=await call("file_read_metadata",{p_file:id}) as {file:Arquivo;storage_path:string};verifiedFile(metadata.file,id);exigir(metadata.storage_path===`${actor.userId}/${id}`,"Arquivo inválido.");const signed=await client.storage.from(FINAL_BUCKET).createSignedUrl(metadata.storage_path,60,{...(download?{download:metadata.file.name}:{})});if(signed.error||!signed.data)throw new AuthGuardError("unavailable");return{url:signed.data.signedUrl,file:metadata.file};},
  async avatar(fileId:string|null,clientId:string){return call("file_avatar_set",{p_file:fileId,p_client_id:clientId},true);},
 };return services;
}
export async function cleanupFiles(config:SupabaseAuthConfig){if(config.supabaseUrl!=="https://rishenjoikgmfubmnfiu.supabase.co")throw new AuthGuardError("unavailable");const client=createPrivilegedClient(config),rpc=client.rpc as unknown as Rpc;const result=await rpc("file_cleanup_candidates",{});if(result.error||!Array.isArray(result.data))throw new AuthGuardError("unavailable");let removed=0,failed=0;for(const item of result.data){if(!object(item)||typeof item.id!=="string"||typeof item.staging_path!=="string"||typeof item.final_path!=="string"||typeof item.remove_final!=="boolean"||!/^[0-9a-f-]{36}\/[0-9a-f-]{36}$/i.test(item.staging_path)||item.staging_path!==item.final_path||item.staging_path.split("/")[1]!==item.id)throw new AuthGuardError("unavailable");const stage=await client.storage.from(STAGING_BUCKET).remove([item.staging_path]);const final=item.remove_final?await client.storage.from(FINAL_BUCKET).remove([item.final_path]):{error:null};if(stage.error||final.error){failed++;continue;}const ack=await rpc("file_cleanup_ack",{p_upload:item.id});if(ack.error)failed++;else removed++;}const log=await rpc("file_cleanup_log",{p_removed:removed,p_failed:failed});if(log.error)throw new AuthGuardError("unavailable");return{removed,failed};}
