import "server-only";
import { NextResponse } from "next/server";
import { readAuthConfiguration } from "../../lib/auth/config";
import { requestAuthServices } from "../../lib/auth/runtime";
import { sameOrigin } from "../../lib/auth/policy";
import { AuthGuardError } from "../../lib/auth/types";
import { ErroDeDominio,exigir } from "../../core/contracts/base";
import { FilesCommitUnknown } from "./files-store";
export const fileHeaders=()=>new Headers({"Cache-Control":"private, no-store, max-age=0",Pragma:"no-cache","X-Content-Type-Options":"nosniff"});
export class FilesSessionChanged extends Error { constructor(){super("A conta mudou. Recarregue para continuar.");this.name="FilesSessionChanged";} }
export async function authorizeFilesRequest(request:Request,headers:Headers,write=false){const config=readAuthConfiguration();if(config.mode!=="supabase")throw new AuthGuardError("demo");if(write&&!sameOrigin(request.headers.get("origin"),config.appOrigin))throw new AuthGuardError("forbidden");const actor=await(await requestAuthServices(true,headers)).gateway.readIdentity();if(!actor)throw new AuthGuardError("unauthenticated");if(actor.mustChangePassword)throw new AuthGuardError("forbidden");const expected=request.headers.get("x-expected-user-id");if(expected!==actor.userId){if(!expected)throw new ErroDeDominio("VALIDATION","Recarregue para confirmar sua conta.");throw new FilesSessionChanged();}return{config,actor};}
export async function readFilesBody(request:Request){exigir(request.headers.get("content-type")?.split(";")[0]?.trim()==="application/json","Envie uma operação JSON.");const reader=request.body?.getReader();exigir(reader,"Informe a operação.");let size=0;const parts:Uint8Array[]=[];try{while(true){const next=await reader.read();if(next.done)break;size+=next.value.byteLength;if(size>16384){await reader.cancel();throw new ErroDeDominio("VALIDATION","Envio excede o limite.");}parts.push(next.value);}try{return JSON.parse(Buffer.concat(parts).toString("utf8")) as unknown;}catch{throw new ErroDeDominio("VALIDATION","Operação inválida.");}}finally{reader.releaseLock();}}
export const fileObject=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==="object"&&!Array.isArray(value);
export const fileUuid=(value:unknown):value is string=>typeof value==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);
export function filesFailure(error:unknown,headers:Headers){let status=503,code="UNAVAILABLE",message="Não foi possível concluir o arquivo. Tente novamente.";if(error instanceof AuthGuardError){status=error.code==="unauthenticated"?401:error.code==="forbidden"?403:503;code=error.code.toUpperCase();message=status===401?"Entre novamente para continuar.":status===403?"Esta operação não está disponível para sua conta.":message;}else if(error instanceof FilesSessionChanged){status=409;code="SESSION_CHANGED";message=error.message;}else if(error instanceof ErroDeDominio){status=error.code==="CONFLICT"?409:error.code==="NOT_FOUND"?404:400;code=error.code;message=error.message;}else if(error instanceof FilesCommitUnknown){code="COMMIT_UNKNOWN";message=error.message;}return NextResponse.json({ok:false,code,message},{status,headers});}
