import "server-only";
import { CalendarProviderError, googleEvent, type CalendarProvider, type RemoteCalendar } from "../../core/calendario";
import { instanteDe } from "../../core/tempo";
import type { GoogleCalendarConfig } from "./google-calendar-security";
const object = (v: unknown): v is Record<string, unknown> => !!v && typeof v === "object" && !Array.isArray(v);
const text = (v: unknown, limit: number) => typeof v === "string" && v.length > 0 && v.length <= limit && !/[\u0000-\u001f\u007f]/.test(v);
function token(value: unknown, now: () => number, requireScope: boolean) {
 if (!object(value) || !text(value.access_token, 8192) || value.token_type !== "Bearer" || !Number.isSafeInteger(value.expires_in) || (value.expires_in as number) < 1 || (value.expires_in as number) > 86400 || (value.refresh_token !== undefined && !text(value.refresh_token, 8192)) || (requireScope && !text(value.scope, 4096)) || (value.scope !== undefined && !text(value.scope, 4096))) throw new CalendarProviderError("unavailable");
 return { access_token: value.access_token as string, refresh_token: typeof value.refresh_token === "string" ? value.refresh_token : null, expires_at: new Date(now() + (value.expires_in as number) * 1000).toISOString(), scopes: typeof value.scope === "string" ? [...new Set(value.scope.split(/\s+/).filter(Boolean))] : null };
}
export function googleCalendarProvider(config: GoogleCalendarConfig, beforeRequest: () => Promise<void>, transport: typeof fetch = fetch, now: () => number = Date.now): CalendarProvider {
 async function request(url: URL, options: RequestInit, revoke = false) {
  if (!((url.origin === "https://oauth2.googleapis.com" && ["/token", "/revoke"].includes(url.pathname)) || (url.origin === "https://openidconnect.googleapis.com" && url.pathname === "/v1/userinfo") || (url.origin === "https://www.googleapis.com" && url.pathname.startsWith("/calendar/v3/")))) throw new CalendarProviderError("unavailable");
  await beforeRequest(); let response: Response;
  try { response = await transport(url, { ...options, cache: "no-store", redirect: "error", signal: AbortSignal.timeout(20_000) }); } catch { throw new CalendarProviderError("unavailable"); }
  if (revoke && (response.ok || response.status === 400)) return {};
  const max = 8 * 1024 * 1024, length = response.headers.get("content-length"); if (length && Number(length) > max) throw new CalendarProviderError("unavailable");
  const reader = response.body?.getReader(); const parts: Uint8Array[] = []; let size = 0;
  try { if (reader) while (true) { const next = await reader.read(); if (next.done) break; size += next.value.byteLength; if (size > max) { await reader.cancel(); throw new CalendarProviderError("unavailable"); } parts.push(next.value); } } finally { reader?.releaseLock(); }
  let value: unknown; try { value = JSON.parse(Buffer.concat(parts).toString("utf8")); } catch { throw new CalendarProviderError("unavailable"); }
  if (!response.ok) { if (response.status === 410) throw new CalendarProviderError("expired_cursor"); if (response.status === 429) throw new CalendarProviderError("quota"); if (response.status === 401 || (response.status === 400 && object(value) && value.error === "invalid_grant")) throw new CalendarProviderError("reauthorize"); if (response.status === 403 && object(value) && object(value.error) && Array.isArray(value.error.errors) && value.error.errors.some(item => object(item) && ["rateLimitExceeded", "userRateLimitExceeded", "quotaExceeded"].includes(String(item.reason)))) throw new CalendarProviderError("quota"); throw new CalendarProviderError("unavailable"); }
  if (!object(value)) throw new CalendarProviderError("unavailable"); return value;
 }
 const authHeaders = (access: string) => ({ Authorization: "Bearer " + access });
 return {
  async exchange(code, verifier) { const value = await request(new URL("https://oauth2.googleapis.com/token"), { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code, code_verifier: verifier, client_id: config.clientId, client_secret: config.clientSecret, redirect_uri: config.redirectUri, grant_type: "authorization_code" }) }); const result = token(value, now, true); if (!result.scopes) throw new CalendarProviderError("unavailable"); return { ...result, scopes: result.scopes }; },
  async refresh(refreshToken) { const value = await request(new URL("https://oauth2.googleapis.com/token"), { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ refresh_token: refreshToken, client_id: config.clientId, client_secret: config.clientSecret, grant_type: "refresh_token" }) }); return token(value, now, false); },
  async profile(access) { const value = await request(new URL("https://openidconnect.googleapis.com/v1/userinfo"), { headers: authHeaders(access) }); if (!text(value.sub, 255) || !text(value.email, 254) || value.email_verified !== true) throw new CalendarProviderError("unavailable"); return { sub: value.sub as string, email: value.email as string }; },
  async calendars(access) { const result: RemoteCalendar[] = []; let page: string | null = null, pages = 0; const seen = new Set<string>(); do { const url = new URL("https://www.googleapis.com/calendar/v3/users/me/calendarList"); url.searchParams.set("maxResults", "250"); url.searchParams.set("minAccessRole", "reader"); url.searchParams.set("fields", "items(id,summary,deleted,accessRole),nextPageToken"); if (page) url.searchParams.set("pageToken", page); const value = await request(url, { headers: authHeaders(access) }); if (!Array.isArray(value.items)) throw new CalendarProviderError("unavailable"); for (const item of value.items) { if (!object(item) || !text(item.id, 1024) || (item.deleted !== undefined && typeof item.deleted !== "boolean")) throw new CalendarProviderError("unavailable"); result.push({ google_id: item.id as string, name: typeof item.summary === "string" ? item.summary.slice(0, 255) : "Calendário", color_key: "calendar", deleted: item.deleted === true }); } pages++; if (pages > 4 || result.length > 1000 || (value.nextPageToken !== undefined && !text(value.nextPageToken, 4096))) throw new CalendarProviderError("quota"); page = typeof value.nextPageToken === "string" ? value.nextPageToken : null; if (page && seen.has(page)) throw new CalendarProviderError("unavailable"); if (page) seen.add(page); } while (page); return result; },
  async events(access, calendarId, query) { const url = new URL("https://www.googleapis.com/calendar/v3/calendars/" + encodeURIComponent(calendarId) + "/events"); url.searchParams.set("singleEvents", "true"); url.searchParams.set("showDeleted", "true"); url.searchParams.set("maxResults", "2500"); url.searchParams.set("fields", "items(id,status,summary,start,end,location,htmlLink,reminders),nextPageToken,nextSyncToken,defaultReminders"); if (query.sync_token) url.searchParams.set("syncToken", query.sync_token); else { url.searchParams.set("timeMin", instanteDe(query.window.start_day)!); url.searchParams.set("timeMax", instanteDe(query.window.end_day)!); } if (query.page_token) url.searchParams.set("pageToken", query.page_token); const value = await request(url, { headers: authHeaders(access) }); if (!Array.isArray(value.items) || value.items.length > 2500 || [value.nextPageToken, value.nextSyncToken].some(item => item !== undefined && !text(item, 4096)) || (value.nextPageToken !== undefined && value.nextSyncToken !== undefined)) throw new CalendarProviderError("unavailable"); const defaults = Array.isArray(value.defaultReminders) ? value.defaultReminders.filter(object).filter(row => typeof row.method === "string" && typeof row.minutes === "number").map(row => ({ method: row.method as string, minutes: row.minutes as number })) : []; return { items: value.items.map(item => googleEvent(item, defaults)), next_page_token: typeof value.nextPageToken === "string" ? value.nextPageToken : null, next_sync_token: typeof value.nextSyncToken === "string" ? value.nextSyncToken : null }; },
  async revoke(refreshToken) { await request(new URL("https://oauth2.googleapis.com/revoke"), { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ token: refreshToken }) }, true); },
 };
}
