import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

export const tokensDirectory = fileURLToPath(new URL("./tokens/", import.meta.url));

const declarations = (values, prefix = "") => Object.entries(values).map(([name, value]) => `  --${prefix}${name}: ${value};`).join("\n");

/** Pure renderer: tokens.json is the only authored value source. */
export function renderTokensCss(tokens) {
  const theme = (name) => `${declarations(tokens.color[name])}\n${declarations(tokens.shadow[name], "elevation-")}`;
  const type = Object.entries(tokens.typography.scale).map(([name, value]) => [
    `  --type-${name}: ${value.fontSize};`,
    `  --leading-${name}: ${value.lineHeight};`,
    `  --weight-${name}: ${value.fontWeight};`,
    `  --tracking-${name}: ${value.letterSpacing};`,
    ...(value.mobileFontSize ? [`  --type-${name}-mobile: ${value.mobileFontSize};`] : []),
  ].join("\n")).join("\n");
  const aliases = [
    "  --color-*: initial;",
    "  --text-*: initial;",
    "  --font-sans: var(--font-family);",
    ...Object.keys(tokens.color.light).map((name) => `  --color-${name}: var(--${name});`),
    ...Object.keys(tokens.typography.scale).flatMap((name) => [
      `  --text-${name}: var(--type-${name});`,
      `  --text-${name}--line-height: var(--leading-${name});`,
      `  --text-${name}--font-weight: var(--weight-${name});`,
      `  --text-${name}--letter-spacing: var(--tracking-${name});`,
    ]),
    ...Object.keys(tokens.radius).map((name) => `  --radius-${name}: var(--r-${name});`),
    ...Object.keys(tokens.shadow.light).map((name) => `  --shadow-${name}: var(--elevation-${name});`),
  ].join("\n");

  return `/* Generated by design-system/generate.mjs from tokens/tokens.json. Do not edit. */
:root {
  color-scheme: light;
${theme("light")}
  --font-family: ${tokens.typography.family};
${type}
${declarations(tokens.radius, "r-")}
${Object.keys(tokens.radius).map((name) => `  --radius-${name}: var(--r-${name});`).join("\n")}
${declarations(tokens.spacing, "space-")}
${declarations(tokens.motion, "motion-")}
${declarations(tokens.zIndex, "z-")}
${declarations(tokens.control)}
}

html[data-theme="dark"] {
  color-scheme: dark;
${theme("dark")}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
    color-scheme: dark;
${theme("dark").split("\n").map((line) => `  ${line}`).join("\n")}
  }
}

@theme inline {
${aliases}
}

/* Only application chrome can use glass. Opaque unless blur is supported. */
.glass-frame {
  background: var(--glass-fallback);
  color: var(--ink);
  border: 1px solid var(--glass-border);
}

@supports (backdrop-filter: blur(1px)) {
  @media (min-width: 768px) and (prefers-reduced-transparency: no-preference) {
    .glass-frame {
      background: var(--glass-surface);
      backdrop-filter: blur(var(--glass-blur)) saturate(var(--glass-saturate));
    }
  }
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: var(--motion-reduced) !important;
    animation-iteration-count: 1 !important;
    transition-duration: var(--motion-reduced) !important;
    scroll-behavior: auto !important;
  }
}
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const tokens = JSON.parse(await readFile(path.join(tokensDirectory, "tokens.json"), "utf8"));
  await writeFile(path.join(tokensDirectory, "tokens.css"), renderTokensCss(tokens));
  console.log("CSS gerado a partir de design-system/tokens/tokens.json.");
}
