import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, writeFile, readFile, rm, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { createHash } from "node:crypto";
import { Readable, PassThrough } from "node:stream";
import { EventEmitter } from "node:events";
import { PGlite } from "@electric-sql/pglite";
import { PERSONAL_REF, REPO_ROOT } from "../../scripts/operations/backup-config.mjs";
import { acceptanceConfiguration, validateAcceptanceManifest, privateAcceptanceDirectory, assertPrivatePermissions, RestoreAcceptanceError } from "../../scripts/operations/restore-acceptance-config.mjs";
import { readRestoredAcceptance, acceptanceReadSql, acceptanceQuery } from "../../scripts/operations/restore-acceptance-reader.mjs";
import { runRestoreAcceptance } from "../../scripts/operations/restore-acceptance-cli.mjs";
const owner="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",item="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",file="cccccccc-cccc-4ccc-8ccc-cccccccccccc",session="dddddddd-dddd-4ddd-8ddd-dddddddddddd",ref="abcdefghijklmnopqrst",stamp="2026-10-09T12:00:00Z",canary="PRIVATE_ACCEPTANCE_CANARY",bytes=Buffer.from("original synthetic fixture bytes"),sha=createHash("sha256").update(bytes).digest("hex");
const manifest={version:1,source_project_ref:PERSONAL_REF,target_project_ref:ref,personal_organization_id:"personal-fixture",archive_sha256:"a".repeat(64),fixture_user_id:owner,vault_item_ids:[item],files:[{id:file,kind:"drive",sha256:sha,bytes:bytes.length}]};
const envelope=length=>({iv:Buffer.alloc(12).toString("base64"),ciphertext:Buffer.alloc(length).toString("base64")});
const vault={revision:"1",header:{user_id:owner,schema_version:1,master:{kdf:{algorithm:"argon2id",memory_kib:65536,iterations:3,parallelism:1,salt:Buffer.alloc(16).toString("base64")},envelope:envelope(48)},recovery:envelope(48),consent_at:stamp,created_at:stamp,updated_at:stamp},items:[{id:item,user_id:owner,version:1,envelope:envelope(16),deleted_at:null,created_at:stamp,updated_at:stamp}]};
const rows={actor_ok:true,vault,files:[{id:file,user_id:owner,kind:"drive",bytes:bytes.length,sha256:sha,storage_path:owner+"/"+file}]};
const jwt=()=>"inert."+Buffer.from(JSON.stringify({sub:owner,session_id:session,iss:"https://"+ref+".supabase.co/auth/v1",exp:Math.floor(Date.now()/1000)+600})).toString("base64url")+".inert";
function env(directory){return{SC_RESTORE_ACCEPT_EXECUTE:"YES",SC_RESTORE_ACCEPT_ISOLATED:"YES",SC_RESTORE_ACCEPT_CONFIRM_PROJECT:ref,SC_RESTORE_ACCEPT_CONFIRM_USER:owner,SC_RESTORE_ACCEPT_SUPABASE_URL:"https://"+ref+".supabase.co",SC_RESTORE_ACCEPT_MANAGEMENT_PAT:"sbp_"+canary,SC_RESTORE_ACCEPT_PUBLISHABLE_KEY:"sb_publishable_"+canary,SC_RESTORE_ACCEPT_STORAGE_KEY:"sb_secret_"+canary,SC_RESTORE_ACCEPT_AUTH_EMAIL:"fixture@example.test",SC_RESTORE_ACCEPT_AUTH_PASSWORD:canary,SC_RESTORE_ACCEPT_PSQL:resolve(directory,"fake-psql"),SC_RESTORE_ACCEPT_PGHOST:"db."+ref+".supabase.co",SC_RESTORE_ACCEPT_PGUSER:"postgres",SC_RESTORE_ACCEPT_PGDATABASE:"postgres",SC_RESTORE_ACCEPT_PGPASSWORD:canary,SC_RESTORE_ACCEPT_PGSSLMODE:"require",SC_RESTORE_ACCEPT_OUTPUT_DIRECTORY:join(directory,"packet")};}
function transport(seen,overrides={}){return async(url,options)=>{seen.push({url,options});if(url.startsWith("https://api.supabase.com/")){const requested=url.split("/").at(-1);return Response.json({ref:requested,organization_id:overrides.organization??manifest.personal_organization_id});}if(url.includes("/token?"))return Response.json({access_token:jwt()});if(url.endsWith("/user"))return Response.json({id:overrides.user??owner,email:"fixture@example.test",is_anonymous:false});if(url.endsWith("/logout?scope=local"))return new Response(null,{status:overrides.logoutFailure?500:204});throw new Error(canary);};}
async function fixture(action){const directory=await mkdtemp(join(tmpdir(),"sc-accept-test-"));try{await action(directory);}finally{await rm(directory,{recursive:true,force:true});}}
test("default help and prepare have no remote/file/process operations even in hosting/CI",async()=>{for(const args of [[],["--help"],["prepare"]]){const out=[];assert.equal(await runRestoreAcceptance(args,{CI:"true",VERCEL:"1",SC_RESTORE_ACCEPT_MANAGEMENT_PAT:canary},value=>out.push(value),{fetch(){throw new Error();},query(){throw new Error();},assertPrivate(){throw new Error();}}),0);assert.equal(JSON.stringify(out).includes(canary),false);} });
test("manifest and execute configuration require an exact isolated personal target, original owner and independent process fields",async()=>fixture(async directory=>{const value=env(directory);assert.deepEqual(validateAcceptanceManifest(manifest),manifest);for(const changed of [{target_project_ref:PERSONAL_REF},{source_project_ref:ref},{fixture_user_id:"unsafe'uuid"},{vault_item_ids:[item,item]},{files:[]},{plaintext:canary}])assert.throws(()=>validateAcceptanceManifest({...manifest,...changed}),/INVALID_ACCEPTANCE_MANIFEST/);for(const changed of [{CI:"true"},{VERCEL_ENV:"production"},{NODE_ENV:"production"},{SC_RESTORE_ACCEPT_EXECUTE:"NO"},{SC_RESTORE_ACCEPT_CONFIRM_PROJECT:PERSONAL_REF},{SC_RESTORE_ACCEPT_CONFIRM_USER:item},{SC_RESTORE_ACCEPT_SUPABASE_URL:"https://"+PERSONAL_REF+".supabase.co"},{SC_RESTORE_ACCEPT_PGHOST:"db."+PERSONAL_REF+".supabase.co"},{SC_RESTORE_ACCEPT_PGUSER:"postgres."+PERSONAL_REF}])assert.throws(()=>acceptanceConfiguration({...value,...changed},manifest));assert.equal(acceptanceConfiguration(value,manifest).pg.PGPASSWORD,canary);assert.throws(()=>acceptanceConfiguration({...value,SC_RESTORE_ACCEPT_MANAGEMENT_PAT:undefined},manifest));}));
test("organization identity rejection occurs before target Auth, SQL or objects and never falls back",async()=>fixture(async directory=>{const calls=[];await assert.rejects(readRestoredAcceptance(acceptanceConfiguration(env(directory),manifest),manifest,{fetch:transport(calls,{organization:"business-fixture"}),query(){throw new Error(canary);},download(){throw new Error(canary);}}),/PERSONAL_ORGANIZATION_MISMATCH/);assert.equal(calls.length,1);assert.equal(calls[0].options.method,"GET");assert.ok(calls[0].url.endsWith(PERSONAL_REF));}));
test("reader verifies owner, exact scoped data and raw streamed file bytes then logs out only its temporary session",async()=>fixture(async directory=>{const calls=[],sql=[];const packet=await readRestoredAcceptance(acceptanceConfiguration(env(directory),manifest),manifest,{fetch:transport(calls),query:async value=>{sql.push(value);return structuredClone(rows);},download:async metadata=>{assert.deepEqual(metadata,{bucket:"second-brain-files",path:owner+"/"+file});return Readable.from([bytes.subarray(0,5),bytes.subarray(5)]);}});assert.equal(packet.fixture_user_id,owner);assert.deepEqual(packet.vault,vault);assert.equal(packet.files_verified,1);assert.equal(JSON.stringify(packet).includes(canary),false);assert.equal(JSON.stringify(packet).includes("fixture@example.test"),false);assert.deepEqual(calls.map(call=>[call.options.method,new URL(call.url).pathname]),[["GET","/v1/projects/"+PERSONAL_REF],["GET","/v1/projects/"+ref],["POST","/auth/v1/token"],["GET","/auth/v1/user"],["POST","/auth/v1/logout"]]);assert.ok(calls.every(call=>call.options.redirect==="error"));assert.equal(new URL(calls.at(-1).url).search,"?scope=local");assert.equal(sql.length,1);assert.match(sql[0],/^begin transaction read only;/);assert.match(sql[0],/rollback;$/);assert.equal(/for share|for update|insert |delete |create |vault_commit|consume_rate_limit/i.test(sql[0]),false);}));
test("wrong owner, malformed/plain payload, entitlement veto and file byte drift fail closed but still revoke the local fixture session",async()=>fixture(async directory=>{for(const failure of ["owner","plain","veto","file"]){const calls=[];const payload=structuredClone(rows);if(failure==="plain")payload.vault.items[0].title=canary;if(failure==="veto")payload.actor_ok=false;let queried=0;await assert.rejects(readRestoredAcceptance(acceptanceConfiguration(env(directory),manifest),manifest,{fetch:transport(calls,failure==="owner"?{user:item}:{}),query:async()=>{queried++;return payload;},download:async()=>Readable.from([failure==="file"?Buffer.from("tampered"):bytes])}));assert.equal(new URL(calls.at(-1).url).search,"?scope=local");if(failure==="owner")assert.equal(queried,0);}}));
test("logout failure blocks success and packet publication",async()=>fixture(async directory=>{const out=[],path=join(directory,"manifest.json");await writeFile(path,JSON.stringify(manifest),{mode:0o600});assert.equal(await runRestoreAcceptance(["execute",path],env(directory),value=>out.push(value),{assertPrivate:async()=>undefined,fetch:transport([],{logoutFailure:true}),query:async()=>structuredClone(rows),download:async()=>Readable.from([bytes])}),1);assert.deepEqual(out,[{ok:false,operation:"restore_acceptance",error:"ACCEPTANCE_LOGOUT_FAILED"}]);assert.deepEqual(await readdir(env(directory).SC_RESTORE_ACCEPT_OUTPUT_DIRECTORY),[]);}));
test("CLI creates a private cipher-only packet after confirmed logout and prints metadata without IDs or credentials",async()=>fixture(async directory=>{const out=[],path=join(directory,"manifest.json");await writeFile(path,JSON.stringify(manifest),{mode:0o600});assert.equal(await runRestoreAcceptance(["execute",path],env(directory),value=>out.push(value),{assertPrivate:async()=>undefined,fetch:transport([]),query:async()=>structuredClone(rows),download:async()=>Readable.from([bytes])}),0);assert.equal(out[0].local_logout_confirmed,true);for(const secret of [canary,owner,item,file,"fixture@example.test"])assert.equal(JSON.stringify(out).includes(secret),false);const stored=JSON.parse(await readFile(join(env(directory).SC_RESTORE_ACCEPT_OUTPUT_DIRECTORY,out[0].packet_name),"utf8"));assert.deepEqual(stored.vault,vault);assert.equal(Object.hasOwn(stored,"password"),false);}));
test("fixed SQL executes read-only against disposable fixtures and selects only approved owner/items/files",async()=>{const db=new PGlite();try{await db.exec("create schema app_private; create function app_private.session_active(uuid,uuid) returns boolean language sql stable as 'select true'; create table public.user_moderation(user_id uuid,must_change_password boolean); create table public.user_entitlements(user_id uuid,feature_key text,allowed boolean); create table app_private.vault_revisions(user_id uuid,revision bigint); create table public.vault_master_keys(user_id uuid,payload jsonb); create table public.vault_items(id uuid,user_id uuid,payload jsonb); create table public.drive_files(id uuid,user_id uuid,kind text,bytes bigint,sha256 text,storage_path text,deleted_at timestamptz,purged_at timestamptz);");await db.query("insert into public.vault_master_keys values($1,$2)",[owner,JSON.stringify(vault.header)]);await db.query("insert into public.vault_items values($1,$2,$3)",[item,owner,JSON.stringify(vault.items[0])]);await db.query("insert into public.drive_files(id,user_id,kind,bytes,sha256,storage_path) values($1,$2,'drive',$3,$4,$5)",[file,owner,bytes.length,sha,owner+"/"+file]);const result=await db.exec(acceptanceReadSql(manifest,session)),value=result.flatMap(reply=>reply.rows).find(row=>Object.hasOwn(row,"jsonb_build_object")).jsonb_build_object;assert.equal(value.actor_ok,true);assert.deepEqual(value.vault.header,vault.header);assert.equal(value.vault.items.length,1);assert.equal(value.files[0].storage_path,owner+"/"+file);await assert.rejects(db.exec("begin transaction read only; update public.drive_files set bytes=1;"));await db.exec("rollback;");}finally{await db.close();}});
test("native SQL transport uses fixed stdin, bounded output and environment-only PG credentials",async()=>{let captured;const child=Object.assign(new EventEmitter(),{stdin:new PassThrough(),stdout:new PassThrough(),stderr:new PassThrough(),kill(){}});const pending=acceptanceQuery({psql:"inert-psql",pg:{PGPASSWORD:canary}},"begin transaction read only; select 1; rollback;",(_,args,options)=>{captured={args,options};child.stdin.resume();child.stdin.on("end",()=>{child.stderr.end(canary);child.stdout.end('{"ok":true}');queueMicrotask(()=>child.emit("close",0));});return child;});assert.deepEqual(await pending,{ok:true});assert.ok(captured.args.includes("--file=-"));assert.equal(captured.args.some(arg=>arg.includes(canary)),false);assert.equal(captured.options.env.PGPASSWORD,canary);assert.equal(captured.options.shell,false);});
test("private paths reject serving/work/sync roots and NTFS ACL failure blocks verification",async()=>fixture(async directory=>{await assert.rejects(privateAcceptanceDirectory(REPO_ROOT,{}, {assertPrivate:async()=>undefined}),/PRIVATE_ACCEPTANCE_PATH_REQUIRED/);await assert.rejects(privateAcceptanceDirectory(join(directory,"OneDrive","packet"),{}, {assertPrivate:async()=>undefined}),/PRIVATE_ACCEPTANCE_PATH_REQUIRED/);const file=join(directory,"acl.json");await writeFile(file,"{}",{mode:0o600});let argumentsUsed;await assert.rejects(assertPrivatePermissions(file,{platform:"win32",environment:{SystemRoot:"C:/Windows"},spawn:(_,args,options)=>{argumentsUsed={args,options};const child=Object.assign(new EventEmitter(),{stdout:new PassThrough(),stderr:new PassThrough(),kill(){}});queueMicrotask(()=>{child.stdout.end("{\"private\":false}");child.stderr.end();queueMicrotask(()=>child.emit("close",1));});return child;}}),/PRIVATE_ACCEPTANCE_PERMISSIONS_REQUIRED/);assert.equal(argumentsUsed.options.env.SC_ACCEPT_ACL_PATH,file);assert.equal(argumentsUsed.args.some(arg=>arg.includes(file)),false);assert.equal(Object.keys(argumentsUsed.options.env).length,2);assert.ok(new RestoreAcceptanceError("CLOSED_ERROR").code);}));
